### PR TITLE
Change `Logic bomb` to `Logic error`

### PR DESCRIPTION
**Pull request by portante**

### CODE REVIEW

**Review by webbnh — APPROVED** [review]
🎉

**Review by ndokos — APPROVED** [review]

**Review by ndokos — CHANGES_REQUESTED** [review]
There seem to be four more bombs:

```
./lib/pbench/agent/tool_meister.py:                f"Logic Bomb! Final path component of the tool directory is"
./lib/pbench/agent/tool_meister.py:                f"Logic Bomb! Final path component of the tool directory is"
./lib/pbench/server/indexing_tarballs.py:                                f"Logic Bomb!  Unexpected tar ball handling "
./lib/pbench/server/report.py:                    ), "Logic Bomb!"
```

**Review by portante — COMMENTED** [review]
Applied latest review feedback.

**Review by webbnh — APPROVED** [review]
👍

**Review by dbutenhof — APPROVED** [review]

**Review by ndokos — APPROVED** [review]

**Pull request merged**
