### PR TITLE
Rename pbench-agent.cfg.example file

### LINKED ISSUE #2343: pbench configuration file does not exists after installation
pbench-agent-0.69.9-24g90314ee7c.noarch

# pbench-register-tool-set
ERROR: failed to fetch tool set, default-tool-set, from the pbench-agent configuration file

Workaround:
cp pbench-agent.cfg.example pbench-agent.cfg

### PR DESCRIPTION
**Pull request by ndokos**
Fixes #2343.

We rename the example config file to pbench-agent.cfg. That allows
the basic operations of the pbench-agent to succeed without further
steps other than installing the RPM. However, moving results to the
server will not succeed, until a proper config file and ssh key file
are installed, so we still expect people to install using Ansible.

### CODE REVIEW

**Review by portante — CHANGES_REQUESTED** [review]
Looks like you deleted the `.example` but did not add the `.cfg`.

**Comment by ndokos** [comment]
D'oh...

**Review by npalaska — DISMISSED** [review]

**Review by portante — APPROVED** [review]

**Review by portante — CHANGES_REQUESTED** [review]
Looks good, but the unit tests no longer pass because it is missing the .example file.  :(

**Comment by ndokos** [comment]
I fixed the unit tests, I believe, so it's ready for the last round :-)

**Review by riya-17 — APPROVED** [review]
Looks Good

**Review by portante — APPROVED** [review]

**Review by portante — CHANGES_REQUESTED** [review]
Needs a rebase.

**Review by dbutenhof — APPROVED** [review]

**Review by riya-17 — APPROVED** [review]

**Review by npalaska — APPROVED** [review]

**Review by portante — APPROVED** [review]

**Pull request merged**
