### PR TITLE
`JSON` logs

### PR DESCRIPTION
**Pull request by portante**
Revamp the server-side logging sub-system to emit JSON log records.

----

Depends on PR #3138.

### CODE REVIEW

**Review by dbutenhof — COMMENTED** [review]
OK, I see a vast array of scattered changes, many of which make sense and none of which seem to be harmful, but I'm not even trying to figure out what's really part of this PR at this point though clearly most of the commits are inherited.

But ... where the heck does this change the log output to JSON? Nowhere, so far as I can see, so what's this really about? Or did I miss some critical linchpin line in this boiling ocean??? 😕

**Comment by portante** [comment]
> OK, I see a vast array of scattered changes, many of which make sense and none of which seem to be harmful, but I'm not even trying to figure out what's really part of this PR at this point though clearly most of the commits are inherited.

Yes, most of this is just PR #3114, since there are some improvements there with the logger references that I don't want to repeat here.

> 
> But ... where the heck does this change the log output to JSON? Nowhere, so far as I can see, so what's this really about? Or did I miss some critical linchpin line in this boiling ocean??? 😕

This is a draft PR, and I wanted to post it because my machine was being flaky and was concerned that if it died I would not have any intermediate progress saved.  =)

That said, the problem with JSON logs is how to get the right loggers to use the new logging handler.  Before I go and change our logger, I want to first fix our use of logging so that it is not hiding the "singleton" nature of loggers (`self.logger` is a bad thing, really), and also make sure we are setting up the loggers correctly at the right times.

Once we correct the current use, it should be fairly easy to use the new format everywhere.

Alas, this is still a "work in progress."

**Comment by portante** [comment]
I have moved the foundational work out of this PR and into #3138.

**Comment by portante** [comment]
Just a passing comment.

**Comment by portante** [comment]
Another drive by ...

**Comment by portante** [comment]
No longer working on pbench.

**Pull request closed without merging**
