### PR TITLE
Remove agent and server activate scripts

### PR DESCRIPTION
**Pull request by ndokos**
The only exception is `pbench-server-activate-create-crontab` which is still used by the server ansible playbooks.

### CODE REVIEW

**Review by portante — CHANGES_REQUESTED** [review]
Can we consider merging this to the `rpm-work` branch since that is where the Ansible roles and playbooks are for the server at this point?  Then we can merge that whole branch to `master` when it is ready.  What do folks think?

**Review by dbutenhof — DISMISSED** [review]
Simplification is always good; why not just get this in and move on from there?

**Comment by ndokos** [comment]
Yes, I jumped the gun: there are unit test failures that need to be dealt with and there is no reason to push this into 0.70.

**Review by riya-17 — DISMISSED** [review]

**Review by npalaska — APPROVED** [review]
This is nice.

**Comment by portante** [comment]
Can you rebase this work and make sure it works properly and then re-request reviews?  I placed it in `Draft` mode until then.

**Comment by portante** [comment]
Replaced by work merge in PR #3100.

**Pull request closed without merging**
