### PR TITLE
Build pbench-tools-kill - Backport of #3405 to b0.72

### LINKED ISSUE #3404: Backport `pbench-tools-kill` to b0.72?
Hunting and killing wayward tool-meister paraphernalia is a pain: @portante added `pbench-tools-kill` to `main` but maybe we should backport it to `b0.72`.

### PR DESCRIPTION
**Pull request by ndokos**
Fixes #3404

Add pbench-tools-kill to the click commands in the agent Makefile.

### CODE REVIEW

**Comment by dbutenhof** [comment]
The failures are ... weird. But they make me wonder if we need to cherry-pick my Flask/Werkzeug `requirements.txt` changes back to b0.72. 😦 Although the signature is bizarre and somewhat different, it's possible that Flask 2.3.1 did partially resolve the issues causing a less direct failure mode.

**Comment by dbutenhof** [comment]
OK, now I don't know what to think. I don't see these on a local branch pulled from b0.72, with Flask 2.3.1 and Werkzeug 2.3.1. Since your build however used Werkzeug 2.3.0 ... it's possible they just published a fix. I'm going to re-submit the build.

**Review by webbnh — APPROVED** [review]
LGTM

So, the tests passed on retry.  (I've restarted the build in #3407.)

**Comment by webbnh** [comment]
The working case used `Werkzeug==2.3.1` while the failing case used `Werkzeug==2.3.0` (all other versions looked the same)...so perhaps we can uncap Flask and Werkzeug on `main` now?

**Comment by dbutenhof** [comment]
> The working case used `Werkzeug==2.3.1` while the failing case used `Werkzeug==2.3.0` (all other versions looked the same)...so perhaps we can uncap Flask and Werkzeug on `main` now?

You might take a look at #3409, which has been up for an hour. 😁

**Comment by webbnh** [comment]
> You might take a look at #3409, which has been up for an hour. 😁

Just did.  (I'm working in chronological sequence...relative things like "an hour" are meaningless....  🙃)

**Review by dbutenhof — APPROVED** [review]

**Pull request merged**
