### PR TITLE
Remove pbench-edit-prefixes

### LINKED ISSUE #1355: Deprecate pbench-edit-prefixes to prepare for removal
We need to remove the `pbench-edit-prefixes` interface entirely in the `pbench-agent` as soon as possible so that we can remove the support for it on the server side eventually after it "ages out" (for some definition of ages).

### PR DESCRIPTION
**Pull request by riya-17**
Fixes #1355 

This PR deals with Removing pbench-edit-prefixes.

### CODE REVIEW

**Comment by riya-17** [comment]
@ndokos can you please review.

**Comment by riya-17** [comment]
@portante @ndokos PR update as requested PTAL

**Comment by riya-17** [comment]
@portante PTAL

**Comment by ndokos** [comment]
@gurbirkalsi : can you take a look at the unit test failure here? `eslint` is complaining about something.

**Comment by gurbirkalsi** [comment]
@ndokos It seems TravisCI is referencing the same linting error seen from the build output in PR #1375 and #1377. Would re-running the TravisCI build resolve this? It seems to be caching the build results from a previous build iteration.

**Comment by ndokos** [comment]
@gurbirkalsi: OK, I'll try redoing it.

**Comment by ndokos** [comment]
@gurbirkalsi: it broke again, but @portante suggested that a rebase of @riya-17's branch is what's missing. @riya-17: can you try rebasing on latest master and seeing if this goes away?

**Comment by riya-17** [comment]
@ndokos I did, it is rebased. I even tried to create another branch and made the same changes and it too showed the same error. Travis failed in that as well. https://github.com/distributed-system-analysis/pbench/pull/1376 this is the link of that closed PR

**Comment by gurbirkalsi** [comment]
Can you try running `eslint --ext .js src && npm run lint:style` from `/web-server/v0.4/` so we can verify if this is error is also reported locally?

**Comment by ndokos** [comment]
@gurbirkalsi: I had to install eslint locally (and that was a pain: doesn't npm resolve dependencies? I had to install a handful of packages and another handful of plugins - should these be installed globally or locally in v0.4?) and I rebased, but I get an error:

```
[v0.4]$  eslint --ext .js src && npm run lint:style
TypeError: Cannot read property 'substring' of undefined
Occurred while linting /home/nick/src/github/pbench/web-server/v0.4/src/components/SearchBar/index.js:57
    at Object.fix (/home/nick/src/github/pbench/web-server/v0.4/node_modules/eslint-plugin-react/lib/rules/jsx-curly-brace-presence.js:129:30)
    at normalizeFixes (/home/nick/src/github/pbench/web-server/v0.4/node_modules/eslint/lib/util/report-translator.js:176:28)
    at args (/home/nick/src/github/pbench/web-server/v0.4/node_modules/eslint/lib/util/report-translator.js:278:18)
    at Object.report (/home/nick/src/github/pbench/web-server/v0.4/node_modules/eslint/lib/linter.js:721:41)
    at reportUnnecessaryCurly (/home/nick/src/github/pbench/web-server/v0.4/node_modules/eslint-plugin-react/lib/rules/jsx-curly-brace-presence.js:117:15)
    at lintUnnecessaryCurly (/home/nick/src/github/pbench/web-server/v0.4/node_modules/eslint-plugin-react/lib/rules/jsx-curly-brace-presence.js:198:9)
    at JSXExpressionContainer (/home/nick/src/github/pbench/web-server/v0.4/node_modules/eslint-plugin-react/lib/rules/jsx-curly-brace-presence.js:278:11)
    at listeners.(anonymous function).forEach.listener (/home/nick/src/github/pbench/web-server/v0.4/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/home/nick/src/github/pbench/web-server/v0.4/node_modules/eslint/lib/util/safe-emitter.js:45:38)
```

**Comment by portante** [comment]
@ndokos, this work seems to now only for the agent side, and it looks good (we have no agent-side unit tests for `pbench-edit-prefix`).

Can you review as well?

Thanks!

**Pull request merged**
