### PR TITLE
Resolves logging error in pbench-server-prep-shim

### LINKED ISSUE #1877: pbench-prep-server-shim-002 wants to write things to an old-style logfile
Installed current server bits on a clean machine and tried all the cron jobs by hand. `prep-shim` failed with the following error:

```
$ flock -n /opt/pbench-server/lib/locks/pbench-prep-002.lock /opt/pbench-server/bin/pbench-server-prep-shim-002
Traceback (most recent call last):
  File "/opt/pbench-server/bin/pbench-server-prep-shim-002.py", line 314, in <module>
    status = main(cfg_name)
  File "/opt/pbench-server/bin/pbench-server-prep-shim-002.py", line 265, in main
    ).open(mode="w") as error_f:
  File "/usr/lib64/python3.6/pathlib.py", line 1183, in open
    opener=self._opener)
  File "/usr/lib64/python3.6/pathlib.py", line 1037, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/lib64/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/srv/pbench-local/logs/pbench-server-prep-shim-002/pbench-server-prep-shim-002.error'
```

It succeeds if I create that directory, but why is it even trying to write into that file? Shouldn't it be logging to syslog?

### PR DESCRIPTION
**Pull request by riya-17**
Fixes #1877

* logs error in new-style
* instead of using an external errorfile used logger.error

### CODE REVIEW

**Review by portante — CHANGES_REQUESTED** [review]
Looks good, just need to get the "lint" removed.

**Review by dbutenhof — APPROVED** [review]
Assuming the tests finish cleanly, looks good.

**Review by portante — APPROVED** [review]
Ship it!

**Review by npalaska — APPROVED** [review]
Lgtm

**Review by ndokos — APPROVED** [review]
Looks good.

**Pull request merged**
