### PR TITLE
Remove the `pbench-agent-config-*` scripts

### PR DESCRIPTION
**Pull request by portante**
The pbench-agent Ansible roles now handle these functions directly.

Builds on PRs

 - #2011 [95b391a5f](https://github.com/distributed-system-analysis/pbench/commit/95b391a5fb0589a4236b4562adfb51d237c5d755)
 - #1997 [41ebcfee5](https://github.com/distributed-system-analysis/pbench/commit/41ebcfee51e3db2192e4727828b3f2b671ffd032)
 - See also issue #1993

### CODE REVIEW

**Review by zulcss — APPROVED** [review]
lgtm, the other branch has to be updated as well

**Review by dbutenhof — DISMISSED** [review]

**Review by ndokos — DISMISSED** [review]

**Comment by portante** [comment]
Rebased ...

**Review by portante — COMMENTED** [review]
No one line of new code added, awesome!

**Review by dbutenhof — APPROVED** [review]

**Review by dbutenhof — APPROVED** [review]

**Review by dbutenhof — APPROVED** [review]

**Review by ndokos — APPROVED** [review]

**Comment by RobertKrawitz** [comment]
I don't believe this will impact containerized agents; am I correct?

**Review by npalaska — APPROVED** [review]

**Pull request merged**
