### PR TITLE
BenchPress Dashboard

### PR DESCRIPTION
**Pull request by gurbirkalsi**
The BenchPress dashboard represents the visualization and analytics aspect of the common data model initiative. The dashboard contains workflows and features from version 2 of the PBench dashboard but only interacts with CDM elasticsearch indices.

### CODE REVIEW

**Comment by portante** [comment]
Same comments as #951.  This patch set needs to be squashed and unnecessary files removed.  348 files seems to be a few too many.

**Comment by gurbirkalsi** [comment]
Just squashed down these changes to one commit. We'll need to restructure the PR once #951 has been merged in master as this PR includes changes merged from that branch.

**Comment by mrsiano** [comment]
@gurbirkalsi can you add some description on it?

**Comment by portante** [comment]
@gurbirkalsi, so lets focus on getting #951 merged first.  Then let's rebase this work on top of that and see how it turns out.

**Comment by gurbirkalsi** [comment]
Closing in favor of tracking changes in the [benchpress dashboard](https://github.com/distributed-system-analysis/benchpress-dashboard)

**Pull request closed without merging**
