### PR TITLE
Speed up source distribution creation

### PR DESCRIPTION
**Pull request by portante**
Layered on top of PR #2684.

### CODE REVIEW

**Comment by portante** [comment]
Filed tracking issue #2688.

**Review by portante — COMMENTED** [review]
Ready for review.

**Review by webbnh — APPROVED** [review]
It's ugly, but it's OK by me.

**Review by npalaska — APPROVED** [review]

**Comment by webbnh** [comment]
> really awkward to maintain

The good news is, given Peter's approach, if we do nothing to maintain it, we'll just get a fixed benefit.  (I.e., there's no correctness issue, there's no _loss_ of performance, etc....there's just performance that we won't get.)

**Pull request merged**
