### PR TITLE
Fix indexing multiple benchmark parameters

### LINKED ISSUE #1176: Indexing errors with trafficgen tarballs
Indexing trafficgen tarballs fails currently (with a test version of pbench-server: v0.58-65). All the trafficgen tarballs ended up in error state 12 with an error message like this:

````
2019-04-23T21:06:34.851026 INFO 27987 140621939472192 pbench-index.pbench-index main 3105 -- Starting /srv/pbench/archive/fs-version-001/perf122/TO-INDEX/trafficgen_advanced-ddos-example_tg:trex-profile_pf:ddos_test1.json_ml:0.002_tt:bs__2019-04-11T08:03:16.tar.xz (size 34817840)
2019-04-23T21:06:44.336501 WARNING 27987 140621939472192 pbench-index.pbench-index _handle_iteration 446 -- result-data-indexing: encountered multiple (2) benchmark parameters in result data JSON file, /srv/pbench-local/tmp/pbench-index.6in5df7i/trafficgen_advanced-ddos-example_tg:trex-profile_pf:ddos_test1.json_ml:0.002_tt:bs__2019-04-11T08:03:16/result.json

019-04-23T21:06:44.336626 ERROR 27987 140621939472192 pbench-index.pbench-index main 3143 -- Other indexing error: 'benchmark_name'
Traceback (most recent call last):
  File "/opt/pbench-server/bin/pbench-index.py", line 3123, in main
    es_res = es_index(idxctx.es, actions, fp, idxctx.logger, idxctx._dbg)
  File "/opt/pbench-server/lib/pbench/__init__.py", line 866, in es_index
    for ok, resp_payload in streaming_bulk_generator:
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 212, in streaming_bulk
    actions, chunk_size, max_chunk_bytes, client.transport.serializer
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/elasticsearch/helpers/actions.py", line 63, in _chunk_actions
    for action, data in actions:
  File "/opt/pbench-server/lib/pbench/__init__.py", line 824, in actions_tracking_closure
    for cl_action in cl_actions:
  File "/opt/pbench-server/bin/pbench-index.py", line 2529, in make_all_actions
    for action in mk_result_data_actions(ptb, idxctx):
  File "/opt/pbench-server/bin/pbench-index.py", line 688, in mk_result_data_actions
    for source, source_id, parent_id, doc_type in sources:
  File "/opt/pbench-server/bin/pbench-index.py", line 423, in _make_source_json
    iter_data, iter_name, iter_number, result_json):
  File "/opt/pbench-server/bin/pbench-index.py", line 449, in _handle_iteration
    benchmark = bm_md['benchmark_name']
    KeyError: 'benchmark_name'

2019-04-23T21:06:44.782470 INFO 27987 140621939472192 pbench-index.pbench-index main 3206 -- Finished /srv/pbench/archive/fs-version-001/perf122/TO-INDEX/trafficgen_advanced-ddos-example_tg:trex-profile_pf:ddos_test1.json_ml:0.002_tt:bs__2019-04-11T08:03:16.tar.xz (size 34817840)

````

The indexer is looking for the benchmark name in the [0] element of the `iter_data['parameters'['benchmark']` array but the name is in the [1] element instead:

````
         ...
         "parameters" : {
            "benchmark" : [
               { ... },
               {
                  "benchmark_name" : "trafficgen",
                  "benchmark_version" : "e58e89b",
                  "primary_metric" : "rx_mpps",
                  "uid" : "benchmark_name:%benchmark_name%-controller_host:%controller_host%"
               }
            ]
         },
         ...
````

The indexer code looks like [this](https://github.com/distributed-system-analysis/pbench/blob/5aabdae899e974cd03479e69de953a98c82a04d9/server/bin/pbench-index.py#L434):
````
        try:
            bm_data = iter_data['parameters']['benchmark']
            bm_md = bm_data[0]
        except Exception as e:
            ...
        else:
            ...

        benchmark = bm_md['benchmark_name']
````

### PR DESCRIPTION
**Pull request by portante**
Some of our benchmark scripts, trafficgen in particular, create multiple benchmark parameter entries in the parameters.benchmark array in result.json.

We now handle this properly by first looking for the entry that has the benchmark_name field in it, and then merging all the other fields while handling the conflicts using "benchmark name" prefixes.

Fixes #1176.

### CODE REVIEW

**Comment by atheurer** [comment]
Anything we should do on agent side for trafficgen to avoid this problem? @k-rister FYI

**Comment by portante** [comment]
The problem appears to arise from two `push`es to the `@benchmark` variable.

**Comment by portante** [comment]
@ndokos, this is ready for review, thanks.

**Comment by portante** [comment]
Rebased; will merge once the unit tests pass in TravisCI.

**Pull request merged**
