### PR TITLE
Pbench React Dashboard

### PR DESCRIPTION
**Pull request by gurbirkalsi**

### CODE REVIEW

**Comment by portante** [comment]
@gurbirkalsi: we can't include any code that is tracked and licensed separately.  So things like the `d3` modules etcetera, have to be removed and including when deployed.  Can you double check for those situations?

**Comment by gurbirkalsi** [comment]
@portante absolutely, the only information within the project code pertaining to third party modules/dependencies is defined in the package.json file. The actual code for these modules are not included in this repo and would be included for deployment as node modules when installing via the package.json file.

**Comment by k-rister** [comment]
Are we intending to fork the existing jschart code into this new v0.4 branch (from the v0.3 code I've been maintaining/updating)?

Also, it looks like there are two separate copies of the code within this PR, why is that?

**Comment by ashishkamra** [comment]
targeting to merge this PR in 0.47 as an alpha feature

**Pull request merged**
