### PR TITLE
rename kvm-spinlock tool to pbench

### PR DESCRIPTION
**Pull request by jeremyeder**
kvm-spinlock was the first script written.  Since then other tools have been incorporated to this script.  It serves multiple purposes now, so let's rename it to something generic, so that there's no confusion.

### CODE REVIEW

**Comment by portante** [comment]
Is this PR a replacement for #134?  And if so, why did we have to close the previous one?

**Comment by jeremyeder** [comment]
Because I broke my local git branch somehow and wasn't sure how to fix it.

**Comment by portante** [comment]
@jeremyeder, I like to avoid proliferating PRs.  If you get stuck like this in the future, I'd be happy to try to help.

**Comment by ndokos** [comment]
I think calling it "pbench" is as confusing as calling it "kvm-spinlock". How about calling it "pbench-generic-tool"?

**Comment by portante** [comment]
Here is a proposal based on top of #287 which finally removes kvm-spinlock as the base tool script: https://github.com/portante/pbench/tree/rename-kvm-spinlock

Once we land #287, I can propose this as a proper PR (not sure how to do that in parallel before #287 is merged).

**Pull request closed without merging**
