### PR TITLE
Native integration of jschart with pbench dashboard

### PR DESCRIPTION
**Pull request by gurbirkalsi**
Utilizes and depends on v1.0.4 of jschart for rendering
formatted json objects containing timeseries data.

Includes styling enhancements for responsiveness with
dashboard run comparison page.

### CODE REVIEW

**Comment by portante** [comment]
@gurbirkalsi, can you post some before/after screen shots as well?

**Comment by gurbirkalsi** [comment]
The .less file was removed because we are using inline JSX styling throughout the dashboard. I will be removing the other .less files tied to routes in a separate PR. Inline JSX styling allows us to take advantage of conditional styling especially in the case of React state changes.

**Comment by gurbirkalsi** [comment]
Before jschart integration (using `timeseries.js` dependency): 

pdash

**Comment by gurbirkalsi** [comment]
After jschart integration: 

pbench_dashboard

**Comment by gurbirkalsi** [comment]
I've also removed the dependency being used for rendering the previous timeseries charts under `src/utils/timeseries.js` in addition to the co-dependencies under `package.json`

**Pull request merged**
