### PR TITLE
Add pbench-logo files

### PR DESCRIPTION
**Pull request by vishalvvr**
PBENCH-220

Add different color (black & colored) and shape(square & circle) logo variants.

### CODE REVIEW

**Review by portante — APPROVED** [review]

**Review by portante — CHANGES_REQUESTED** [review]
If we pull the SVG into the tree, should we also be using them somehow?

**Review by dbutenhof — CHANGES_REQUESTED** [review]
> If we pull the SVG into the tree, should we also be using them somehow?

I had the same thought, though I don't specifically object to "staging" the resources intended for use later, I wonder why it's worth a separate PR?

Also, (more importantly) keep in mind the rules for the Jira automation, please. The Jira issue reference must be:

1. In the BRANCH name, e.g., `origin/PBENCH-220`;
2. In the PR *title* (which I think is fairly ugly and makes the title harder to read)
3. In a **git log message**

This PR references a Jira issue in the PR description, which doesn't count.

Note that mine usually *also* reference the Jira ticket in the PR description, but only because I write my full PR description as my initial git log message, which GitHub uses by default as the PR description. (I just remove line breaks in the GitHub description editor so that it wraps nicely in the Markdown view.)

I recommend something like:

```
Add pbench logo files

PBENCH-220

Add different color (black & colored) and shape(square & circle) logo variants.
```

You can fix this with a `git rebase -i`, modifying your git log comment for the existing commit, or by adding a second commit.

As a side-note, I'm somewhat against using Jira sub-tasks at this point just due to the incredible annoyance at sprint planning time. In order to avoid carrying all the *completed* sub-tasks of an incomplete story forward along with the *incomplete* sub-tasks, the story needs to be manually cloned, and each incomplete sub-task needs to be moved to the new clone through a tedious multi-step process.

We plan stories, not sub-tasks. We should use sub-tasks only where:

1. A story requires multiple PRs, *and*
2. All of those PRs can be completed together within a single sprint.

**Review by webbnh — APPROVED** [review]
_Grrr, GitHub:  there doesn't seem to be a way to comment on a file which doesn't contain **lines**...._

`dashboard/src/assets/logo/color-circle.svg` looks funny, to me.  Perhaps it's because I'm looking at it against the "transparent" background instead of in situ on a real page, but it strikes me that it's not properly centered in the circle.  I'm not absolutely positive, but I _think_ the "center" of the logo should be between the `e` and the `n` and not at the base of the pointer.

Anyway, that detail aside, I think it's cool that we have these assets, and we need to store them somewhere (even if the are not all immediately used by the Dashboard), and this seems like as good a place as any.

**Comment by vishalvvr** [comment]
when I tried renaming the branch this issue got auto closed :)
Let me open a new PR.

**Pull request closed without merging**
