### PR TITLE
Correct server RPM spec, remove obsolete server container builds, correct pbench-in-a-can container builds

### PR DESCRIPTION
**Pull request by portante**
* Correct `workingDir` for pbench-server container
   * Remove unneeded API and `sshd` port mappings.
 * Add missing `hostname` RPM dependency
 * Check RPM path as early as possible
   * And remove unneeded references to `sshd`.
 * Remove obsolete container build method
 * Remove unused server RPMs from COPR

### CODE REVIEW

**Review by dbutenhof — APPROVED** [review]
Sigh. While I appreciate the idea of separating concerns, my concern is that doing so *after* review means reviewers need to read it all twice, which isn't ideal. 😵‍💫

**Comment by portante** [comment]
> Sigh. While I appreciate the idea of separating concerns, my concern is that doing so _after_ review means reviewers need to read it all twice, which isn't ideal. 😵‍💫

Wasn't the other PR a `Draft` mode PR?

**Comment by portante** [comment]
That is to say, I did not invite or request anybody to review PR #3081 because it is not ready for review.

**Review by webbnh — APPROVED** [review]
👍

**Comment by dbutenhof** [comment]
> > Sigh. While I appreciate the idea of separating concerns, my concern is that doing so _after_ review means reviewers need to read it all twice, which isn't ideal. face_with_spiral_eyes
> 
> Wasn't the other PR a `Draft` mode PR?

Of course you're technically correct, but that practice could be said to provide some disincentive for previewing draft PRs, which I don't think was necessary in this case.

In any case, I did approve, so 'nuff said.

**Pull request merged**
