### PR TITLE
Correct method of verifying log messages

### PR DESCRIPTION
**Pull request by portante**
The `verify_logs` method in `test_requests.py` now looks for the expected warning message explicitly.

### CODE REVIEW

**Comment by portante** [comment]
@Maxusmusti, this should fix the CI job failures found in PR #2468.

**Review by webbnh — APPROVED** [review]
🥇

**Comment by portante** [comment]
Sorry, no changes, just added @webbnh as a co-author.

**Comment by webbnh** [comment]
> Sorry, no changes, just added @webbnh as a co-author.

Hmmm...I'll have to take back the 🥇, then -- can't have any appearance of favoritism.  (And, I'll abstain from approving. 😁)

**Review by ndokos — APPROVED** [review]

**Review by dbutenhof — APPROVED** [review]
In general I'd rather *not* have unit tests looking at the log; and in several of these tests we're expecting duplicate text from the JSON response and a log, which is extra redundant.

But, sure; this at least cleans up the previous fragile logic for testing what I'd rather not test, so good. 🍤

**Review by npalaska — COMMENTED** [review]
:+1:

**Pull request merged**
