### PR TITLE
Remove GraphQL pass-through API

### PR DESCRIPTION
**Pull request by MVarshini**
PBENCH-716

Remove GraphQL pass-through API

As backend support for favorites changed remove GrapghQL API

### CODE REVIEW

**Review by dbutenhof — APPROVED** [review]
Very thorough! This looks great.

I've been forgetting to update my functional `test_connect.py` with new APIs (e.g., the `/server/audit`), and this will become more important when we start running Python functional tests (hopefully soon).

Although we don't necessarily need to be maintaining the legacy test setups (under `server/bin/state`), I'm glad that you removed the GraphQL boilerplate.

**Comment by webbnh** [comment]
Black appears to be objecting to the formatting in `lib/pbench/test/unit/server/test_endpoint_configure.py` and `lib/pbench/test/unit/server/test_requests.py`.

**Review by webbnh — DISMISSED** [review]
Looks good to me...other than the Black issues.  (Looks like some trailing whitespace and a missing blank line.)

**Review by npalaska — DISMISSED** [review]
Looks good. Just need some `black` formatting

**Review by siddardh-ra — DISMISSED** [review]
:+1:

**Review by siddardh-ra — APPROVED** [review]
:+1:

**Review by dbutenhof — APPROVED** [review]

**Review by riya-17 — APPROVED** [review]

**Review by webbnh — APPROVED** [review]
👍

**Comment by webbnh** [comment]
Unfortunately, Varshini, GitHub is still showing this branch as having merge conflicts.  Could you make sure that your local repo's version of the `main` branch is up to date and then try rebasing your branch on it?

**Comment by dbutenhof** [comment]
> Unfortunately, Varshini, GitHub is still showing this branch as having merge conflicts, so I cannot merge it into `main`.
> 
> Could you make sure that your local repo's version of the `main` branch is up to date and then try rebasing your branch on it?

Stale view, Webb? I'm not seeing any conflicts, and right now everything is green.

**Comment by webbnh** [comment]
> Stale view, Webb? I'm not seeing any conflicts, and right now everything is green.

I had to do a force-reload of the page in my browser!  (A restart of the browser and even a system restart was not enough!  Wow....)  Thanks for doing the merge.

**Comment by dbutenhof** [comment]
> > Stale view, Webb? I'm not seeing any conflicts, and right now everything is green.
> 
> I had to do a force-reload of the page in my browser! (A restart of the browser and even a system restart was not enough! Wow....) Thanks for doing the merge.

GitHub can be remarkably resourceful when it comes to keeping stale data sometimes...

**Pull request merged**
