### PR TITLE
Fix tool argument handling (v0.69)

### PR DESCRIPTION
**Pull request by portante**
Fixes issue #1751, where tools with multiple arguments only have the first argument passed to the tool command.

This PR is only for the `b0.69` branch.

### CODE REVIEW

**Review by ndokos — DISMISSED** [review]
LGTM -  do we need to turn off black for this? The tests are failing because of it.

**Comment by portante** [comment]
> Do we need to turn off black for this? The tests are failing because of it.

I back-ported PR #1768 to this branch, which should fix that problem.  The agent and server tests also failed, but they seem to be an ordering problem we have not locked down in the unit tests.

**Comment by portante** [comment]
@ndokos, so I've had to add a couple more commits to address the test failures.  Seems like we have a working environment now.

**Review by zulcss — APPROVED** [review]
lgtm

**Review by ndokos — APPROVED** [review]

**Pull request merged**
