### PR TITLE
Ansible playbook for using pbench

### PR DESCRIPTION
**Pull request by chaitanyaenr**

### CODE REVIEW

**Comment by jeremyeder** [comment]
Hey, we've got a little wrapper script that we use to setup pbench across a list of machines:
https://github.com/openshift/svt/blob/master/openshift_scalability/pbench-register.sh

I think this could be turned into an ansible role.  The key concern I have is that we not become reliant on ansible at all -- retain existing capabilities, but augment them with an ansible role which people could use to speed things up (parallelism of ansible), and leverage their existing inventory files. /cc @portante

**Comment by jeremyeder** [comment]
@chaitanyaenr any thoughts on moving this forward?

**Comment by chaitanyaenr** [comment]
@jeremyeder  Yes. Please let me know if I need to make any changes.

**Comment by chaitanyaenr** [comment]
@jeremyeder @portante should I create an ansible role?

**Comment by portante** [comment]
@jeremyeder, not sure why you don't want to rely on Ansible.  What is the problem with that?

**Comment by jeremyeder** [comment]
@portante I meant merging this PR? Why isn't it merged?

**Comment by portante** [comment]
@jeremyeder, it is not merged yet because we have prioritized indexing work and server stability work over reviewing this work.

Can we have folks try it out and report back what they find?

Once we have folks reporting back after use, we can merge it.

Then we have to determine if this lands in the packaging of pbench-agent (which I think it does) and/or if we deliver this via Galaxy (which also seems like a good thing).

**Comment by jeremyeder** [comment]
Yes, I tried it out.  It works as expected.  Here are my notes:

This should be the default:
- ```ansible-playbook -i Inventory file --extra-vars '{"CONTROLLER":"yes", "REMOTE":"yes"}' pbench.yml```

- Run pbench-list-tools as the last task?
- Add a pbench-clear-tools mode?
- Don't try to install/update by default (or create a mode that opts-in to this behavior).
- Add an example inventory file that includes the extra-vars (command line is not friendly)

I have a list of several RFEs we'd need if we wanted to make use of this playbook in our more pointed scenarios, but those do not impact the basic functionality implemented in this PR.

**Comment by chaitanyaenr** [comment]
@jeremyeder @portante I modified the pr to register tool-set by default, added clear-tools mode, added an example inventory file that includes the extra-vars,  removed pbench-install-agent role which installs pbench-agent. How about adding pbench-agent-install role to galaxy?

**Comment by jeremyeder** [comment]
To me it should verify that a version of pbench-agent is installed (rpm -q), but not try to update it, and most importantly, not to go and talk to a yum repo somewhere unless explicitly told to operate in that mode.

**Pull request merged**
