### PR TITLE
Use recommended Flask application name

### PR DESCRIPTION
**Pull request by portante**
See "About the First Parameter" at:
  https://flask.palletsprojects.com/en/2.2.x/api/#flask.Flask

See also https://github.com/distributed-system-analysis/pbench/pull/3114/commits/889cbfd7b8dc3380a5cde80ac36aacd6252d71b4 in PR #3114.

### CODE REVIEW

**Review by webbnh — APPROVED** [review]
👍

**Comment by portante** [comment]
Seems our functional tests are flaky.

**Comment by webbnh** [comment]
> Seems our functional tests are flaky.

I haven't been having problems (and most of your PRs seem to be doing OK), but I have been seeing this reported after they run successfully:
```
  py39: commands succeeded
  congratulations :)
time="2023-01-13T21:49:46Z" level=warning msg="StopSignal SIGTERM failed to stop container pbench-in-a-can_3109-postgresql in 10 seconds, resorting to SIGKILL"
da893e95ed7ed2e1388ced1f6e863e7f743b0192cb834427001cfbc5b08b2809
da893e95ed7ed2e1388ced1f6e863e7f743b0192cb834427001cfbc5b08b2809
Error: Image used by 826e6b7181c1327f024bd90d8639371b6cc1bd8095b901f448d9a5cfcab8e652: image is in use by a container
```
So, apparently it takes the Server more than 10 seconds to shut down in an orderly fashion, and, apparently, it takes a non-trivial amount of time to die after being killed such that one of the subsequent five Podman commands (`podman image prune`?) is failing, as well.

**Review by dbutenhof — APPROVED** [review]

**Review by dbutenhof — APPROVED** [review]

**Review by webbnh — APPROVED** [review]
Sorry...apparently my approval didn't "stick".

**Pull request merged**
