### PR TITLE
Get the current Agent container build working again

### PR DESCRIPTION
**Pull request by webbnh**
Apparently, the Agent container builds aren't working any more.  This PR restores them to working order.

The principal changes:

- The container build depends on the `pbench.repo.j2` template from the Ansible collection...which, apparently, moved recently (#2991).
- The "implicit" pattern rules don't seem to be working, so I converted them to "static" pattern rules (which are uglier, but, well, they _work_...).
- Added a second repository to the `agent/containers/images/repo.yml.j2` template for the "auxillary" RPMs.

I also made some smaller changes:
- Added Fedora-36 to the list of default targets
- The `-TEST` suffix will now _really_ disappear when it's not needed.
- Removed some redundant dependencies on the `pkgmgr-clean` target.
- Tweaked a code comment.

### CODE REVIEW

**Review by ndokos — COMMENTED** [review]
LGTM but there is an additional problem: it is not enough to use `pbench-0.72` or `pbench-0.72-test` as *the* repo. We need the old plain `pbench` repo for the auxiliary RPMs. Or we need to build the auxiliary RPMs in every `pbench-X.XX[-test]` repo which is an unappealing prospect.

**Review by ndokos — APPROVED** [review]

**Review by portante — CHANGES_REQUESTED** [review]
The changes all look fine, with the burning question of why we needed those `Makefile` target changes?  I took the individual other changes and added them in a separate branch (see https://github.com/portante/pbench/commits/alt-pr-3013) and was able to use this command to run through all the targets quickly without problems:

    BUILDAH_ECHO=echo make COPR_USER=portante TEST=test clean all 2>&1 | less -S

In addition, I was also curious about the `pkgmgr-clean` changes, as they were not obvious to me.

**Comment by webbnh** [comment]
> The changes all look fine

You've "requested changes" without citing anything specific which you think needs to be changed.  🙁

> why we needed those `Makefile` target changes?

Which ones?  The removal of the `pkgmgr-clean` dependencies or the conversion of the implicit pattern rules to static pattern rules?

I removed the former because they are redundant and unnecessary.  (That didn't _need_ to be done, but I saw no reason not to do it.)

I converted the latter because, without the conversion, the build wouldn't work in Nick's environment and with the conversion it now works.  (I'll defer to you on whether that makes the change "needed".)

**Comment by portante** [comment]
@webbnh, the branch I posted works fine without all the static Makefile changes.

**Comment by webbnh** [comment]
> the branch I posted works fine without all the static Makefile changes.

I'm not surprised.  I believe that it worked for me when I originally put those targets into place.  But, does it work for @ndokos?

**Comment by portante** [comment]
I don't think we should make the change because of one person's environment.  Let's dig a little deeper to avoid such a radical change.

**Comment by webbnh** [comment]
> I don't think we should make the change because of one person's environment.

That's easy to say when it's working for you!  😆

> Let's dig a little deeper to avoid such a radical change.

It's not a radical change.  I'll grant that it's ugly-looking, but it's actually a _simplifying_ change, as static pattern rules are much easier to understand and apply than implicit pattern rules.

Anyway, I just pulled your branch and ran the command you suggested...it appeared to be happy, but it ran quite quickly and doesn't appear to have actually built any container images.  😕

**Comment by webbnh** [comment]
> it ran quite quickly and doesn't appear to have actually built any container images.

Oh, let me guess:  the `BUILDAH_ECHO=echo` prefix prevents it from _actually_ doing anything....

**Comment by portante** [comment]
So that you can verify all the make targets quickly.

**Comment by portante** [comment]
I'd rather not take in such a big change.

**Comment by portante** [comment]
Superseded by PR #3018.

**Comment by ndokos** [comment]
I haven't the foggiest why I was getting errors before and as I mentioned in #3018, I am not getting those errors when I run with those changes. Perhaps some of it was that I was getting shellacked with problems from podman not finding the image I wanted, quay.io rejecting me at every possible opportunity, my confusion over `fedora-36` vs `fedora-36-all` and I don't remember what else. But I thought @webbnh had reproduced the error I was getting with the Makefile:

```
[nick@alphaville ~/.../agent/containers/images]$ make all
dnf clean all
97 files removed
./verify-tags *-tags.lis
make: *** No rule to make target 'centos-7-all-tagged', needed by 'all'.  Stop.
```

**Comment by webbnh** [comment]
> I thought @webbnh had reproduced the error I was getting with the Makefile

I thought I had too.  But, two days later, I was unable to reproduce it again.  🤷

**Comment by ndokos** [comment]
Ah, well - some mysteries will remain ... mysterious.

**Pull request closed without merging**
