### PR TITLE
use a smaller port number increment to allow greater scalability

### PR DESCRIPTION
**Pull request by bengland2**
This proposed change will resolve problem described in pbench issue #375 .  We define a port number increment variable instead of hard-coding it to 1000.  Then we set this variable to 10 instead of 1000.  When I ran this, the problem I described with running 14 client-server pairs disappeared.  This will be essential to test configurations with more than 7 servers (2 NIC ports/server).  

This does not resolve the problem where the port number is already in use, I expect this to happen as we use more and more port numbers.  It would not be hard to insert a check to see if the port number is currently in use on the target system before assigning it.

### CODE REVIEW

**Comment by portante** [comment]
@bengland2, seems reasonable, but we need to update the unit tests.

**Comment by bengland2** [comment]
With @ndokos advice, the CI test passed.  Most of the code diff listed above is actually the diff in the expected test output, which has port numbers everywhere.

**Comment by ndokos** [comment]
@atheurer: any objections to this? I'd like to merge it for v0.40.

**Comment by bengland2** [comment]
@atheurer why do we need to use multiple port numbers for pbench-uperf?  Why not start a listener on every host with the standard port number, then just have clients bind to whatever IP address is in --client and connect to whatever address is in --server, and just use one listener port number for everything?

**Comment by bengland2** [comment]
@atheurer  I just noticed that if I set port number gap to zero, IT STILL WORKS.  The only error I get is this:

    found uperf pid 1654484 on 172.18.64.240:20000, killing

See [here](http://pastebin.com/rLnjKdbw) for full command and result.  It just rolls right along.  This is consistent with my experience with netserver listener - you only need one of them/host.  This totally eliminates the problem of some port numbers being available and simplifies firewall management - you only have to open up the one port number, which is trivial to do (pbench-fio does it).  I'm going to submit an update to the code to do this, which will address the other issue where pbench-uperf turns off the firewall.  We could add a parameter to set the port number so that if the default port 20000 is taken, we can still run the test.  OK?

**Comment by bengland2** [comment]
I'm going to resubmit a clean pull request in 10 min since I got out of sync here with distributed-system-analysis/pbench master and the merge was too painful.

**Comment by atheurer** [comment]
This different port number was done because we really wanted a completely different process ID, because we wanted to be able to bind each copy of the server to a potentially different NUMA node.  So, having multiple copies of the benchmark required its main port to be different.

Having one uperf server process and having multiple clients connect to it is not good enough.  We can't control the placement of the threads spawned by uperf, because there is only 1 uperf process.  With multiple copies, we can then control the placement of each copy.

The original thought behind the spacing (1000) of ports  was I thought the threads launched for multi-instance (multiple network streams per copy of uperf server), would be incremented from the main port.  That does not seem to be the case, for example, port list on a host with 2 copies of uperf and 16 instances (streams) each:

0.0.0.0:21000
0.0.0.0:22000
0.0.0.0:32970
0.0.0.0:33471
0.0.0.0:34628
0.0.0.0:35332
0.0.0.0:36217
0.0.0.0:36238
0.0.0.0:36376
0.0.0.0:36435
0.0.0.0:37308
0.0.0.0:37309
0.0.0.0:37656
0.0.0.0:37948
0.0.0.0:38879
0.0.0.0:38937
0.0.0.0:39249
0.0.0.0:39319
0.0.0.0:39343
0.0.0.0:39660
0.0.0.0:40083
0.0.0.0:40673
0.0.0.0:41002
0.0.0.0:41723
0.0.0.0:41797
0.0.0.0:42984
0.0.0.0:43184
0.0.0.0:43851
0.0.0.0:44329
0.0.0.0:44786
0.0.0.0:45928
0.0.0.0:45956
0.0.0.0:46143
0.0.0.0:46493

So, IMO, we still need to support multiple copies of the uperf server, so we can bind them individually, but we should only have to increment the port by "1" for each extra copy.

The reason the port number was incremented regardless, was that when specifying a server by wither hostname or IP, even if they are different, does not guarantee it is a different host.  This is the case where we run between two hosts with several adapters, just on different IP subnets.  So, we just increment the port number when iterating over the entire host list, to ensure there is never overlap.

**Comment by bengland2** [comment]
Andrew, NUMA pinning is a valid reason, which I was not aware of.  I saw the **numactl** command in there but wasn't sure what implications of that were, this is why I at-signed you.  OK, we'll go back to using separate port numbers.   It's more complicated to get it right (i.e. firewall rules, and what if that port number isn't available?).  

Would be great if there was a command line parameter to enable/disable it, with default being disabled (not current behavior, but the norm for most applications).    Let's not do that here.

Part of why I closed the PR - sometimes it's easier to just start over again with a fresh rebased PR, particularly with the problems in the gold (regression test output) files where git won't merge them.

**Comment by ndokos** [comment]
PR #390 (which is effectively the same as this PR with conflicts resolved and unit tests passing) was merged.

**Pull request closed without merging**
