### PR TITLE
Fixes to the systemd service file plus a service file for RHEL7

### LINKED ISSUE #1802: Fix systemd pbench-server unit file to handle RHEL 7 SCL environments
The systemd pbench.service file deals with the generic case (python3 without SCL, i.e. the Fedoras and RHEL8) but it does not deal with RHEL7 and SCL.

### PR DESCRIPTION
**Pull request by ndokos**
Fixes #1802

The service file has to deal with scl on RHEL7, so we provide a separate one.

### CODE REVIEW

**Review by portante — CHANGES_REQUESTED** [review]
> The service file has to deal with scl on RHEL7, so we provide a separate one.

How does this provide a separate one?  Is there a missing file in the commit?

**Comment by ndokos** [comment]
Argh - forgot to add it.

**Review by portante — CHANGES_REQUESTED** [review]
And what is the mechanism that determines which service file to put into place in this commit?

**Comment by ndokos** [comment]
The mechanism is not implemented yet, but I was going to do it with an extra role in ansible. I've changed the status of the PR to draft until I add the role.

**Review by portante — CHANGES_REQUESTED** [review]
Looks good, just needs a rebase and we can ship it!

**Comment by ndokos** [comment]
Rebased.

**Review by portante — APPROVED** [review]
Ship it!

**Review by dbutenhof — APPROVED** [review]

**Review by npalaska — APPROVED** [review]

**Comment by npalaska** [comment]
oh boy, the util-script test-53 failed I have seen it failed once with my PR, I feel it just randomly fails sometime

**Pull request merged**
