### PR TITLE
Works regarding the index of sar data in ES 5.x, template for sar data and json templates for grafana dashboard.

### PR DESCRIPTION
**Pull request by tenstormavi**
For testing purpose I am sending these files. When these get successfully reviewed and archit's works will get merged, will send a new one.

### CODE REVIEW

**Comment by arcolife** [comment]
@tenstormavi I already had a PR for this https://github.com/distributed-system-analysis/pbench/pull/229 

Also, I see that this PR contains some stuff that should technically go on top of https://github.com/distributed-system-analysis/pbench/pull/176

Grafana work, IMHO should be in a separate branch than the sar indexing stuff.

**Comment by tenstormavi** [comment]
@arcolife I mentioned above that it is solely for testing purpose; mainly to see my work which I did on top of yours. It is also labeled as "DO NOT MERGE". 

@portante and @ndokos wants to see what I have done till now. So they suggested me to send a PR of my work. And will send a new PR after your work will get merged.

**Comment by tenstormavi** [comment]
@portante @ndokos changes made as requested.

These have 2 new templates named: panel_template, target_template

All the templates now have target values in them, so target values will go first into target template and then it(target values embedded in target templates) goes into panel templates. When all the target templates get embedded into panel template completely, finally it(panel template) will goes into dashboard template, to create the whole dashboard.

**Comment by portante** [comment]
Closing because this work is very old and to rebase it will be difficult.

**Pull request closed without merging**
