### PR TITLE
Keep only one systemd service file

### PR DESCRIPTION
**Pull request by npalaska**
Address bugs found during the server installation on RDU2 intlab-008 (Oct 13/2020 2:00 – 3:00pm EST)

### CODE REVIEW

**Review by dbutenhof — COMMENTED** [review]
Don't we need a change to keep the installer/configuration from trying to use the `pbench-server.service.rhel7`??

And if the `requests` problem was just using `pip` instead of `pip3` on RHEL7, why didn't we have problems with the other dependencies? Odd.

**Review by ndokos — CHANGES_REQUESTED** [review]
I'm nto sure that we want all of these in the same PR. And the `pbench-server.service.default` file should pprobably be renamed to `pbench-server.service`. Plus the ansible role will need changes for that. Can you take care of the service files in this PR? The RPM/Ansible changes should probably go in through the rpm-branch.

**Comment by npalaska** [comment]
@ndokos this PR is is against RPM-work branch itself

**Comment by npalaska** [comment]
@ndokos only the service file related changes are now addressed in this PR

**Review by portante — APPROVED** [review]

**Comment by ndokos** [comment]
`pip` was a red herring: the spec file does `python3 -m pip -r requirements.txt` which is equivalent to `pip3 install -r requirements.txt`, so no change is needed in that.

**Comment by npalaska** [comment]
yes I reverted those changes

**Review by ndokos — APPROVED** [review]

**Pull request merged**
