### PR TITLE
Add performance co-pilot tool

### PR DESCRIPTION
**Pull request by atheurer**
-assumes distribution provides pcp packages
-does not use pcp-native distributed collection, but pbench --remote option
-generates csv's and htmls for all metrics
-pcp's pmlogger archive (archive.[0-9] are kept in case user wants to use other tools like pcp2graphite

### CODE REVIEW

**Comment by ndokos** [comment]
Can you rebase your branch on current master? I get a VERSION of 0.35 when I pull.

**Comment by ndokos** [comment]
When I try to register pcp, I get a slew of "Cannot connect" messages:

```
# pbench-register-tool --name=pcp
attempting to install pcp-gui
Creating config file "/opt/pbench-agent/config/pmlogger.conf" using default settings ...
pmprobe: Cannot connect to PMCD on host "local:": Connection refused
...
.....pmprobe: Cannot connect to PMCD on host "local:": Connection refused
pmprobe: Cannot connect to PMCD on host "local:": Connection refused
.pmprobe: Cannot connect to PMCD on host "local:": Connection refused
pmprobe: Cannot connect to PMCD on host "local:": Connection refused
pmprobe: Cannot connect to PMCD on host "local:": Connection refused

pcp tool is now registered in group default
```

Any ideas?

**Comment by fche** [comment]
@ndokos, `service pmcd start`.

**Comment by ndokos** [comment]
Thanks! Should that be added to the registration code?
In any case, things seem to work (in the sense that I get non-trivial results), even though the registration complains. I guess the service is started/stopped as part of start/stop-tools.

**Comment by fche** [comment]
Either the registration script should ensure `pmcd` is running (with a `service` command) - or - error out conclusively and advise the user to start the server herself and retry.

**Comment by atheurer** [comment]
I'll rebase with master and look into the error.  This error is odd as I never had that occur with my testing.

**Comment by k-rister** [comment]
On 03/08/2016 01:09 PM, Andrew Theurer wrote:
> I'll rebase with master and look into the error. This error is odd as I
> never had that occur with my testing.
> 

Could it be that you manually enabled the service while developing the code?

-- 
Karl Rister
<krister@redhat.com>

**Comment by ndokos** [comment]
It only happens on first registration, and pcp-gui needs to be installed *and* there is no
/opt/pbench-agent/config/pmlogger.conf file. Doing this:

	if [ ! -e $pmlogger_conf ]; then
		service pmcd start
		/usr/libexec/pcp/bin/pmlogconf -c -r $pmlogger_conf
		service pmcd stop
	fi

in tool-scripts/pcp fixes it.

**Comment by atheurer** [comment]
OK, I now realize what the problem is.  Before we did not call pmloggerconf, and we never got these errors, thus having pcmd running was not necessary at register/install time.  Now that we use pmlogger we need that service.  We don't want to wait until tool-start time to call pmlogger because it can take way too long to finishm and we want the tool to start immediately.

**Comment by atheurer** [comment]
FWIW, I did not realize this pull request would close when I re-based my branch.  In order to re-base and not completely screw up the log, I did a "git rebase master", then I had to delete and re-create the branch on github site.  If I re-base, then "git push" (without delete), the commit log has repeat commits in it. @ndokos @portante I think this is what happened a long time ago when I tried a rebase (repeat commits).  An alternative is to "git merge upstream/master" on my local system, then "git push", but I thought @portante preferred a "git rebase".

**Comment by portante** [comment]
@atheurer, hmm, I am not sure what happened here.  If you want, we can work it out tomorrow when I am more available to talk and track this down.

**Comment by ndokos** [comment]
@atheurer, what does

```
git remote -v
```

say?

**Comment by atheurer** [comment]
# git remote -v
origin	git@github.com:atheurer/pbench.git (fetch)
origin	git@github.com:atheurer/pbench.git (push)
upstream	git@github.com:distributed-system-analysis/pbench.git (fetch)
upstream	git@github.com:distributed-system-analysis/pbench.git (push)

**Comment by portante** [comment]
@atheurer, if you create your branches as follows:
```
git checkout -b work-for-a upstream/master
```
Then you will likely not have this problem in the future.  Then you just do perform, `git remote update`, and follow it with a, `git status`, to see where you are compared to what is in upstream master.  When you are behind a few commits, you use `git rebase` to lay your branch changes on top of upstream master.

You can fix that today by making sure your local branch is tracking upstream/master instead of origin/master, like so:
```
git branch --set-upstream-to=upstream/master work-for-a
```
Then do `git remote update; git rebase` to get your changes layered on top.

The only time I have found using `git merge` is necessary is when we have two repositories with interleaved changes from more than one person.

**Comment by atheurer** [comment]
@portante do I then push directly to upstream? git push upstream work-for-a
If so, am I now eliminating the origin (my github repo) completely?

This seems quite different from the "fork a repo" process I (and others?) have been using.

**Comment by portante** [comment]
@atheurer, setting the tracking branch is just about how you keep one branch up-to-date with respect to another.

So you still would `git push origin work-for-a` to push your branch to your github repository, and then issue the PR from there.

**Pull request closed without merging**
