### PR TITLE
Add pbench agent dependencies list 

### PR DESCRIPTION
**Pull request by vishalvvr**
These are the package dependencies for pbench-agent.
This list will help for installing and/or packaging pbench-agent from sources.
Also, this list has an upstream link for packages if the package is not packaged
into any distro users can use this upstream project link to know more.

[Preview](https://github.com/vishalvvr/pbench/blob/PBENCH-221/docs/pbench-agent-package-dependencies-list.md)

PBENCH-221

### CODE REVIEW

**Review by webbnh — COMMENTED** [review]
This seems fine as far as it goes, but I'm wondering whether we want to add it to the repo.  

It's not obvious to me how this list (and its references) will be kept up to date; there is no verbiage in the file explaining what it is, when it was created, or what it is to be used for; and, it strikes me that this is more or less intended to capture information for a one-time use -- namely, to create a build or packaging script which will encapsulate and use this information -- and once that is accomplished, this file will just rot.

So, it really seems like this should be a Google doc or similar until we can put it to use, and then after that we can ignore it in favor of the actual "code" which uses this information.

[Also, you seem to be using a merge model to keep this branch up to date with `main` which produces a rather interesting history of commits; please try rebasing your branch on the end of `main` instead of merging commits from `main` into your branch.]

**Comment by pravins** [comment]
This is a part of our documentation, so as with other documentation i think this will also remain here inside the repo.
Might be in the future other distro users will help to add/update dependencies :)

**Comment by dbutenhof** [comment]
> This is a part of our documentation, so as with other documentation i think this will also remain here inside the repo. Might be in the future other distro users will help to add/update dependencies :)

That's OK; but as permanent documentation,

1. We need to be sure this is *maintained*, which is going to be a tricky proposition;
2. The document needs more context to explain what the table *means* and what one might expect to be able to *do* with the information.

**Comment by webbnh** [comment]
> This is a part of our documentation [...]  Might be in the future other distro users will help to add/update dependencies :)

This information will be used to create Python requirements files, RPM spec files, Dockerfiles, or other build scripts, which will be machine readable, testable, and will likely be kept up to date (i.e., or the CI will break).  Anyone who wants to add a new distro will most likely modify or clone those files -- they won't go to this file for that information.  And, so, this file is likely to become out of date quickly, and then it will possibly be worse than useless.

So, I applaud this work, and I look forward to it being used to correct and enhance our build system(s)...but I don't see any value to adding this file to the repo, other than on a temporary basis (in which case perhaps it belongs in a Jira issue instead, which can be closed one it has been applied to our code).

**Review by portante — CHANGES_REQUESTED** [review]
If you could find a way to automate the generation of this table in our documentation from our RPM spec files and requirements.txt files, that would be great.

If you have some other way to making this table maintainable by others in some fashion, could you describe that in this PR?

**Comment by vishalvvr** [comment]
As discussed with the team, this doc/file will be stale periodically if not automatically generated.

Since this is not an urgent requirement, I am closing this PR for now.

**Pull request closed without merging**
