### PR TITLE
Pcp

### PR DESCRIPTION
**Pull request by atheurer**
Adds pcp tool

### CODE REVIEW

**Comment by atheurer** [comment]
PR #182 is required before this pull request is merged.  PCP installs with no version specified, because we do not maintain the package within pbench. PR #182 resolves an issue where check_install_rpm returned code "1" when the package was already installed, and the package version was not provided with check_install_rpm

**Comment by ndokos** [comment]
@atheurer: I've got a pcp unit test case (needs an updated unittests script in tool-scripts/postprocess). I've tested on a branch with master + atheurer-sar + atheurer-PR#182 + atheurer-pcp.

**Comment by atheurer** [comment]
ok I think you can send me a pull request for that, or send it to me directly.

**Comment by portante** [comment]
@ndokos, @atheurer, I have posted @ndokos's patch against @atheurer's working branch in his repo.  So now he can merge that, and then issue a PR using that.

**Comment by ndokos** [comment]
I created a new PR #205 for this that adds a (rudimentary) unit test and squashes all the commits down to one to simplify the history. I wanted to include this in v0.37 so apologies if I stepped on anybody's toes. I'm closing this PR and merging #205. Please let me know if there are any problems.

**Pull request closed without merging**
