### PR TITLE
Fix sync status management

### PR DESCRIPTION
**Pull request by dbutenhof**
PBENCH-1027

Rescue a few minor fixes and diagnostics from the languishing #3103.

### CODE REVIEW

**Review by webbnh — APPROVED** [review]
👍 

(I think this is the _third_ PR I've seen some of these changes in...happy merging!)

**Comment by dbutenhof** [comment]
> +1
> 
> (I think this is the _third_ PR I've seen some of these changes in...happy merging!)

I worked this out debugging my stream-drainer, and then ported it into audit; and I hope that goes in first (if anyone actually reviews it, because if I have to rebase again I think I'll let it stew until next year)... but since other PRs are suffering I'd like to get this in.

**Review by npalaska — DISMISSED** [review]

**Review by webbnh — APPROVED** [review]
👍  (GitHub says there've been no changes since my last review.)

**Comment by dbutenhof** [comment]
> +1 (GitHub says there've been no changes since my last review.)

Which is true, since we retroactively included a massive merge with no changes!

**Review by portante — APPROVED** [review]

**Pull request merged**
