### PR TITLE
add memory usage pidstat graphs

### PR DESCRIPTION
**Pull request by jeremyeder**
Add memory vsz and rss graphs.  Here's an example with this patched pidstat-postprocess.  A stress binary allocates 1GB and frees it, in a loop.  Graphs look good.

pidstat_memory

### CODE REVIEW

**Comment by portante** [comment]
Looks good to me.  Nit on using spaces instead of tabs.  But we need to update the unit tests to have some sample files.

**Comment by lukas-vlcek** [comment]
Works like a charm!
How can I help you get this merged?

**Comment by portante** [comment]
@lukas-vlcek, unit tests need to pass with the generated files verified from the existing data.

**Comment by lukas-vlcek** [comment]
Looking into build log I see:
````
Testing pidstat-postprocess under sample pidstat ...
Only in /tmp/GenData/pidstat/csv: memory_usage_resident_set_size.csv
Only in /tmp/GenData/pidstat/csv: memory_usage_virtual_size.csv
Only in /tmp/GenData/pidstat: memory_usage-average.txt
Only in /tmp/GenData/pidstat: memory_usage.html
FAIL - pidstat
````
Does it mean I can simply grab missing files from <http://pbench.perf.lab.eng.bos.redhat.com/results/dhcp-2-178/pbench-user-benchmark_test2_2016-05-17_08:03:47/1/reference-result/tools-default/dhcp-2-178/pidstat/> or is there a different way how missing files in golden folder should be generated?

**Comment by ndokos** [comment]
@lukas-vlcek: pretty much. I usually eyball them for sanity and sometimes massage them a bit for reproducibility (e.g. timestamps) but otherwise as you describe: it's a manual procedure and a very simplistic unit test system (but if you would like to contribute a better one, please go ahead :-) - we would all welcome it!)

**Comment by jeremyeder** [comment]
possible to merge?

**Comment by lukas-vlcek** [comment]
Has the unit test been implemented? If yes, I would like to check it out so that I know how exactly it has to be prepared going forward. If not, I am willing to help with this as I would love to see this feature being merged too.

**Comment by jeremyeder** [comment]
Oh, no it hasn't.  I've not done this myself either but it appears the process is just to copy new sample files to agent/tool-scripts/postprocess/samples/pidstat/

Is this correct?

**Comment by portante** [comment]
Copying new sample files is okay as long as somebody verifies that the values in the generated files are correct.

**Comment by jeremyeder** [comment]
I think I did it.

**Comment by jeremyeder** [comment]
can this be merged?

**Comment by portante** [comment]
@jeremyeder, something is not adding up.  Why do the voluntary and non-voluntary context switches charts disappear?

Something is not right with this patch, not sure it is your changes though.  Something else is disturbed by the changes.

**Comment by portante** [comment]
Closing in favor of #262.

**Pull request closed without merging**
