### PR TITLE
Include "common" pytests in tox exec-unittests

### PR DESCRIPTION
**Pull request by dbutenhof**
Fix a minor but critical typo...

### CODE REVIEW

**Comment by dbutenhof** [comment]
```
------------------------------ coverage ------------------------------
---------------------- coverage: failed workers ----------------------
The following workers failed to return coverage data, ensure that pytest-cov is installed on these workers.
gw0
gw1
[...every worker...]
```

Just because I enabled `common` pytests? Hmm...

**Review by webbnh — DISMISSED** [review]
Other than the fact that it appears to result in mayhem, I have no problem with this change.... 🤣

**Comment by portante** [comment]
> Just because I enabled `common` pytests?

Heh, I'll take a look.

**Comment by portante** [comment]
Try adding an empty `__init__.py` to `lib/pbench/test/unit/common`.

**Comment by portante** [comment]
And add:

 * lib/pbench/test/unit/server/database/__init__.py
 * lib/pbench/test/unit/server/query_apis/__init__.py

**Review by portante — CHANGES_REQUESTED** [review]
Looks like we need `__init__.py` files in all the module directories under the `lib/pbench/test` hierarchy.

**Comment by portante** [comment]
See https://github.com/dbutenhof/pbench/pull/3.

**Review by npalaska — APPROVED** [review]

**Comment by dbutenhof** [comment]
> Try adding an empty `__init__.py` to `lib/pbench/test/unit/common`.

So, object lesson: *Python* itself no longer requires empty `__init__.py` files in modules, but **Pytest** (or maybe just `pytest_cov`?) still does. Arrgh. 😬

**Pull request merged**
