### PR TITLE
Capture uperf-server logs for debugging

### PR DESCRIPTION
**Pull request by portante**
We also now run the `pbench-uperf` client and server with the `-v` flag
to get verbose output.

### CODE REVIEW

**Comment by portante** [comment]
@atheurer, what do you think about always running `uperf` with the `-v` flag?  It was really useful to figure out what was happening with a client that appeared not to be able to connect to the server.

**Comment by portante** [comment]
@atheurer, can you officially "approve" this request as well?

**Comment by atheurer** [comment]
I do t think I can do that unless I am an official reviewer. Can you add me and then I can approve

**Comment by portante** [comment]
I think you are already added.  There should be a review button in the top right of your screen.

**Comment by portante** [comment]
Just merging anyways.

**Pull request merged**
