### PR TITLE
Static references are incorrect

### PR DESCRIPTION
**Pull request by MVarshini**
Issue https://github.com/distributed-system-analysis/pbench/issues/3128

Static references are incorrect

Broken Pbench logo image after visiting 404 page

### CODE REVIEW

**Review by siddardh-ra — APPROVED** [review]

**Review by dbutenhof — COMMENTED** [review]
Would changing `"homepage": "."` to `"homepage": "dashboard"` solve the problem? When we were talking yesterday, I was hoping that might.

Ideally, I'd love to be able to move away from hardcoding the dashboard deployment path in the dashboard code. That would allow us to deploy multiple dashboard on the same IP/port for testing and for CD A/B deployment ... which right now we're unable to support.

If that doesn't work, we'll need to work out how to do it; but getting this working via brute force is acceptable in the short term. (We already have hardcoded "dashboard" paths in the Javascript anyway, so these are only making it slightly worse.)

**Review by portante — CHANGES_REQUESTED** [review]
Looks good, though I have never understood why the dashboard code needs to know and/or control the URL it is deployed under.

Can you use `git rebase` instead of a `git merge` to remove the merge commit?

**Review by webbnh — APPROVED** [review]
👍

**Review by dbutenhof — APPROVED** [review]
We really do need to figure out how to make the dashboard code location independent; but this is OK as an immediate fix for the specific problem.

**Review by portante — APPROVED** [review]

**Pull request merged**
