### PR TITLE
Adds unit test for Month Select component

### PR DESCRIPTION
**Pull request by Anisha1234**
Code Coverage Report:
```
 File                  |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line 
components/MonthSelect |      100 |      100 |       75 |      100 |                   |
index.js               |      100 |      100 |       75 |      100 |                   |
```

Coverage reports are currently retrieved in Jest by running the following command: umi test ./src/components ./src/pages --verbose --maxWorkers=1 --runInBand "--coverage"

### CODE REVIEW

**Comment by gurbirkalsi** [comment]
@Anisha1234 Which functions are not being covered with these tests here?

**Comment by Anisha1234** [comment]
> @Anisha1234 Which functions are not being covered with these tests here?

@gurbirkalsi I am not sure. There are two functions and I covered both of them. Also, there are no uncovered lines so I am not being able to figure out.

**Comment by portante** [comment]
Let's try to get #1411 merged with working unit tests and E2E tests in TravisCI before we take this additional work in.  Thanks!

**Comment by portante** [comment]
@Anisha1234, can you rebase this work and verify the unit tests and e2etests pass for you?n

**Pull request merged**
