### PR TITLE
Improves oc (OpenShift) command data collection.

### PR DESCRIPTION
**Pull request by jtudelag**
Collects now:
* top nodes
* top pods
* describe nodes

I have found this new data crucial for the performance test I'm conducting, so hopefully is handy enough for 
 a wider audience.

### CODE REVIEW

**Comment by jtudelag** [comment]
@portante PTAL when you some cycles.

**Comment by jtaleric** [comment]
Should this really be in Stockpile @portante ?

**Comment by portante** [comment]
> Should this really be in Stockpile @portante?

Yes, all of `oc_data_once()` looks like a good candidate to land in [stockpile](https://github.com/redhat-performance/stockpile), and then use `pbench-* --sysinfo=all` to collect it all.

@jtudelag, can you take a look at that and see what you think?

**Comment by jtudelag** [comment]
@portante I will do my best. https://github.com/redhat-performance/stockpile is completely new to me. So let me have a look. I might need some guidance.

**Comment by jtudelag** [comment]
@portante, @jtaleric  do you want me to enhance the current [stockpile ocp cluster topology role](https://github.com/redhat-performance/stockpile/blob/master/roles/openshift-cluster-topology/tasks/main.yml), or create a new role from scratch?

**Comment by portante** [comment]
> do you want me to enhance the current stockpile ocp cluster topology role

Seems like we can enhance the current role as a first pass.

**Comment by portante** [comment]
@jtudelag, any progress on this front?

**Comment by jtudelag** [comment]
@portante yeah, sorry I completely forgot about this, working on it.

**Comment by jtudelag** [comment]
PR here: https://github.com/redhat-performance/stockpile/pull/62

**Comment by portante** [comment]
Closing in favor of the `stockpile` PR [#62](https://github.com/redhat-performance/stockpile/pull/62).

**Pull request closed without merging**
