### PR TITLE
Allow sar to support two different versions of mem_usage stats

### PR DESCRIPTION
**Pull request by atheurer**
We can now postprocess the older version (fewer stats) and the newer versions

### CODE REVIEW

**Comment by portante** [comment]
Can we add sample data in the unit tests to help verify this?

**Comment by ndokos** [comment]
I just sent to Andrew a tarball with sample/gold data in the new format.

**Comment by ndokos** [comment]
If this is to supersede PR#171, we'll need to change the package version in tool-scripts/sar as well. Or are we going to merge both? WIll PR#171 need rebasing?

**Comment by atheurer** [comment]
Sorry, I forgot we had other files from PR171.  Let me pull those in to this PR/branch

**Comment by atheurer** [comment]
This pull request now contains the version change for sar.  The pull request also includes the new unittest files that Nick has provided.  I don't think we need to merge the original pull request any more.

**Comment by ndokos** [comment]
OK - thanks! I'll add a note to PR#171 and close it.

**Comment by jeremyeder** [comment]
Sweet!  Thanks @atheurer !

**Pull request merged**
