### PR TITLE
Agent base

### PR DESCRIPTION
**Pull request by atheurer**
A couple things for our base script:
fix tagging of functions in logging
a new benchmark install script

### CODE REVIEW

**Comment by atheurer** [comment]
@portante could you review and merge?

**Comment by portante** [comment]
Can you get the unit tests to pass first? ;)

**Comment by atheurer** [comment]
Yes, just pushed unittest changes

**Comment by portante** [comment]
@atheurer, so nothing is using the new logging function yet?

**Comment by atheurer** [comment]
@portante nothing uses install_benchmark_systems yet.  There will be other pull requests for modified benchmark scripts after most of the consolidated functions are written.  I am testing these functions with cmd line calls to these new functions directly.

**Comment by portante** [comment]
@atheurer, okay, let's try to code up a simple set of unit tests for this new method then and include them with it when we submit.

**Comment by portante** [comment]
@atheurer, is this still relevant?

**Comment by atheurer** [comment]
no, let's close

**Pull request closed without merging**
