### PR TITLE
Change sync-satellite reception area

### PR DESCRIPTION
**Pull request by riya-17**
PBENCH-594

### CODE REVIEW

**Review by portante — CHANGES_REQUESTED** [review]
Looks good!  Could we consider a small change?  See https://github.com/riya-17/pbench/pull/6.

**Comment by portante** [comment]
@riya-17, I think I have a elegant fix for the unit test failures ... I'll post shortly.

**Comment by portante** [comment]
@riya-17, okay, got this all working in https://github.com/riya-17/pbench/pull/7.

**Comment by portante** [comment]
So `test-5.2` and `test-10` are failing in the CI, but not locally ... at least I didn't see them fail the last time I ran it.

Checking now.

**Comment by portante** [comment]
> So `test-5.2` and `test-10` are failing in the CI, but not locally ... at least I didn't see them fail the last time I ran it.
> 
> Checking now.

If you merge https://github.com/riya-17/pbench/pull/7 these test failures should be fixed.

**Review by portante — CHANGES_REQUESTED** [review]
You'll need https://github.com/riya-17/pbench/pull/7 to make this all work.

**Comment by riya-17** [comment]
Hey @portante I added a change due to which it must be failing. I needed to check something. Merging it.

**Review by portante — APPROVED** [review]
Looks good, but somebody else need to review besides me.

**Review by dbutenhof — APPROVED** [review]

**Comment by portante** [comment]
Added the "do not merge" label until @ndokos has a chance to review as well.

**Review by ndokos — APPROVED** [review]

**Comment by ndokos** [comment]
Reviewed, approved and removed the "DO NOT MERGE" label.

**Pull request merged**
