### PR TITLE
Fixes to ansible roles (fwd port of #3478)

### PR DESCRIPTION
**Pull request by ndokos**
- repo.name -> repo.tag

- assert that `pbench_repo_name' is defined (users have to define it in their inventory)

- use `latest' when installing packages and stop ansible-lint from complaining about it

These fixes are incorporated into the `pbench.agent` collection, v1.0.11, available from Galaxy.

PBENCH-1129

### CODE REVIEW

**Review by dbutenhof — APPROVED** [review]

**Review by webbnh — APPROVED** [review]
👍

**Comment by dbutenhof** [comment]
Rebasing will pick up Webb's legacy test fix. 😆

**Comment by webbnh** [comment]
> Rebasing will pick up Webb's legacy test fix. 😆

I'm not sure that that fix covers _this_ problem.  😢

**Comment by ndokos** [comment]
So what do they keep in Area-52?

**Comment by webbnh** [comment]
> ```
> "pbench-tool-meister-stop" failed to execute successfully (exit code: 124)
> ```

I believe that that is a timeout.  I'm inclined to say that that is nondeterministic behavior resulting from environmental effects.

**Pull request merged**
