### PR TITLE
Benchmark Summary JSON files and MoonGen benchmark support

### PR DESCRIPTION
**Pull request by portante**
This is work from Andrew Theurer where we helped him tease out the MoonGen changes from the summary JSON file changes, squashing them into two commits.  The other four commits address to development environment bugs (unit test execution and Perl 5.14+ support), a developer doc start, and an update to what we ignore in-tree.

### CODE REVIEW

**Comment by atheurer** [comment]
I am fine with merging as long as we can build test RPMs and get a few people to test, in particular uperf, since all of the summary reports have changed.

**Comment by atheurer** [comment]
We have a problem with test type mearts for uperf, which I will need to fix before we merge this

**Comment by atheurer** [comment]
I also see a problem with uperf.html graphs.  uperf-postprocess generates csv files (from the new json data) in order to use gen_data().  The first graph is a throughput graph, but it has a different time series for each data series.  gen_data() does not seem to detect this [anymore?] and attempts to graph some of the time series as actual data. I recall this mode of graphing, where there is a unique time series for each data series, to be uncommon (uperf.html might be the only one with this).  I wonder if this has been not working since we moved to new graphing routines and just noticed it now.

**Comment by k-rister** [comment]
Do you mean something along the lines of the following:

timestamp1,data1,timestamp2,data2,timestamp3,data3,...

If so that is definitely broken in my new graphing as it expects the following:

timestamp,data1,data2,data3

**Comment by atheurer** [comment]
Yes, the old graphing supported that.  I believe @portante was the one who implemented it

**Comment by k-rister** [comment]
I can fix that, I just need to know what the convention is to know that is what is being specified.  I assume there some special header information in the first row?

**Comment by ndokos** [comment]
@k-rister: it's controlled by the $csvtype variable in GenData.pm: 1 is the standard format, 2 is the
ts1, d1, ts2, d2, ... format, starting at around line 107.

**Comment by ndokos** [comment]
@atheurer: COPR is taking its time, but I'm building a pbench-agent RPM (0.38-2ged3733e) in the pbench-test repo, based on this branch. You should be able to update with something like:

yum/dnf --enablerepo=copr-pbench-test update pbench-agent

when it's done (I'll yell when that happens).

**Comment by k-rister** [comment]
I created an issue ( #259 ) for the graphing problem and pushed a fix into my PR ( #250 )

**Comment by atheurer** [comment]
@portante should I just reply here with a patch for uperf mearts issue, then you can apply to your branch?

**Comment by atheurer** [comment]
`diff --git a/agent/bench-scripts/pbench-uperf b/agent/bench-scripts/pbench-uperf
index d70c6a3..c781003 100755
--- a/agent/bench-scripts/pbench-uperf
+++ b/agent/bench-scripts/pbench-uperf
@@ -104,6 +104,7 @@ function gen_xml {
                echo "    <transaction iterations=\"1\">"
                echo "      <flowop type=\"accept\" options=\"remotehost=$h protocol=$proto\"/>"
                echo "    </transaction>"
+               echo "    <transaction duration=\"$runtime\">"
                echo "      <flowop type=\"read\" options=\"count=16 size=$size\"/>"
                echo "    </transaction>"
                echo "    <transaction iterations=\"1\">"`

**Comment by atheurer** [comment]
I think /opt/pbench-agent/bench-scripts/postprocess/process-iteration-samples is missing from the RPM.  Not sure why.  Can anyone who has installed the test RPM check if they have it?

**Comment by atheurer** [comment]
Couple of commits we need to add:
fix uperf mearts
https://github.com/atheurer/pbench/commit/eed2323fdf13aeaffefeb78b3b8edf8b02976ec9

fix response log file name regex
https://github.com/atheurer/pbench/commit/9f46d5e0140ecad8a464b893f537c91c3c07e63e

**Comment by ndokos** [comment]
@atheurer: process-iteration-samples is indeed absent: it got caught by a faulty exclusion pattern when making the tarball.

I'm going to make a new RPM with the pattern fixed and the additional two commits you identified.

**Comment by ndokos** [comment]
New RPM in the COPR pbench-test repo: pbench-agent-0.38-5g41adc8c
with process-iteration-samples included and the two fixes cherry-picked.

**Comment by atheurer** [comment]
@ndokos here is the commit for using significant figures in process-iteration-samples.  I used 4 for now (we can change easily):
https://github.com/atheurer/pbench/commit/6e73345b855b2e6b9b2b0c2c1540a60e1785b857

**Comment by ndokos** [comment]
I have a "clean-at-json" branch in my clone of the dsa pbench repo:

https://github.com/ndokos/pbench/tree/clean-at-json

that squashes all of this (except for the developer doc change of @portante - that should be folded into PR #266) into a single commit. It includes the fixes required for the unit tests to pass (not only for these scripts but also some server unit tests that were turned off previously, and now have been turned back on): https://travis-ci.org/ndokos/pbench/builds/139625801

:Not sure how we want to proceed: jiust continue with this PR? or close it and open a new one against the "clean" branch?

**Comment by ndokos** [comment]
Test RPM based on the clean-at-json branch (see comment above) is available on the COPR pbench-test repo: pbench-agent-0.38-7g932679a.src.rpm

**Comment by ndokos** [comment]
Closing this. PR #269 (a superset of this one, including fixes for the unit tests) was merged instead.

**Pull request closed without merging**
