### PR TITLE
Emit full exception on backup directory failure

### PR DESCRIPTION
**Pull request by portante**

### CODE REVIEW

**Review by dbutenhof — DISMISSED** [review]
My first thought was "why not just convert it to `logger.exception`" ... but we know it came from the `os.mkdir` so that would probably be pointless volume.

**Comment by dbutenhof** [comment]
Except ... ha, ha:

```
black --check ...
[1mwould reformat /home/pbench/server/bin/pbench-backup-tarballs.py[0m
[1mOh no! 💥 💔 💥[0m
[1m1 file would be reformatted[0m, 30 files would be left unchanged.[0m
FAILED: black --check .
```

**Review by webbnh — APPROVED** [review]
👍

**Review by portante — COMMENTED** [review]
Fixed the `black` issue.

**Comment by portante** [comment]
> My first thought was "why not just convert it to `logger.exception`" ... but we know it came from the `os.mkdir` so that would probably be pointless volume.

And this is really just a back-port of what is on the `main` branch.

**Review by dbutenhof — APPROVED** [review]

**Review by webbnh — APPROVED** [review]
👍

**Pull request merged**
