### PR TITLE
Rework the agent functional tests

### PR DESCRIPTION
**Pull request by portante**
The functional tests were only for the agent.  There is no need to run them for the server side.

This partially fixes issue #2647 by always having an agent environment for the functional tests.

This is foundational work for PR #2551.

### CODE REVIEW

**Comment by portante** [comment]
This PR is layered on top of PRs #2646 and #2644.  We'll pull this out of `Draft` mode when those PRs land.

**Review by dbutenhof — COMMENTED** [review]
Pretty simple when stripped of the common layers reviewed elsewhere. Looks fine, but there's no point in approving until those two go in.

**Review by webbnh — APPROVED** [review]
What Dave said...except for the part about approving.  😁

**Review by portante — COMMENTED** [review]
Ready for final review.

**Review by webbnh — APPROVED** [review]
👍

**Review by dbutenhof — APPROVED** [review]

**Pull request merged**
