### PR TITLE
add formatted getting-started guide; Fixes #2

### LINKED ISSUE #2: Improve README to describe various parts of pbench
We need to improve the README file that ends up displayed on GitHub, and move the documentation to the gh-pages side of the house.

### PR DESCRIPTION
**Pull request by arcolife**

### CODE REVIEW

**Comment by portante** [comment]
@ndokos, @atheurer, can you comment as well?  I merge when we have collected all the comments and we are all comfortable with it.

**Comment by portante** [comment]
@arcolife, nice work.  Just a couple of comments in-line, and are there instructions somewhere for how you generated the HTML page from the `.org` files?  I am guessing the Makefile does that, but we should put a README somewhere calling that out.

**Comment by atheurer** [comment]
This looks good.  My only concern is this assumes a environment where a package & web repository are already set up, right?

**Comment by portante** [comment]
@atheurer, I think I see what you mean, we should probably fix there here.

**Comment by portante** [comment]
Replaced by #68.

**Pull request closed without merging**
