### PR TITLE
Add blazemeter taurus bench-script

### PR DESCRIPTION
**Pull request by rflorenc**
This adds support for executing blazemeter taurus (bzt) performance tests.

The main dependency is bzt, which can be installed using the pip package management system for python.

http://gettaurus.org/docs/Installation/#CentOS

### CODE REVIEW

**Comment by jeremyeder** [comment]
Thanks Ricardo, here are my notes from looking it over:

* Can you commit a README file with documentation, including some of the more complex options?
* There's no --help option?
* RHEL ships PyYAML-3.10-11.  I hope that will suffice?
* Usage of pip for bzt...this would be the first time we're using pip in pbench.  For the rest of the benchmarks, we've created RPMs.  I think we should be consistent about that.
* Looking at http://gettaurus.org/docs/Installation/ I see we will need a few other packages pulled in as well (wait, are these dependencies for building bzt via pip?  Anyway I think right now pbench_benchmark scripts automatically install any dependencies via yum/rpm.  This script should do the same.

**Comment by portante** [comment]
@rflorenc, thanks this is a great start.  We can work through the pip -> rpm dependencies.

**Comment by atheurer** [comment]
Really glad to see a new benchmark script here.  I think this is a good time to create a checklist for benchmarks.  We can maintain this list in the top of the benchmark script, so users know what common pbench features are present in that script.  For example:

[y/n] package dependency/installation management
[y/n] tools start/stop/post-processing calls
[y/n] multiple benchmark iterations
[y/n] multiple test samples per benchmark iteration (to compute average and stddev)
[y/n] unittest
[y/n] iteration result metrics in indexable json format (no benchmarks have this yet)

others?

Good examples of the first 5 features are in pbench_uperf

**Comment by rflorenc** [comment]
@all, Thanks for the feedback!
@jeremyeder ,
- Sure, I'll commit the README file soon.
- The help option is already included. Run it with -h or --help.
- Yes, that version of PyYAML is OK.
- Yes, those are the base dependencies required to install bzt through pip.

**Comment by rflorenc** [comment]
I totally agree that we should be consistent with the way the rest of the bench scripts are solving their dependencies through rpm, but in this case since it's a python wrapper for an external tool (also python) you would potentially avoid problems in the future.

This is where bzt takes its dependencies from:
[https://github.com/Blazemeter/taurus/blob/master/setup.py#L66]

Pip takes care of updating/upgrading the app as needed from the python package index.

**Comment by rflorenc** [comment]
@jeremyeder , @portante 
PyYAML module dependency is not longer a dependency, since bzt accepts json scenario files as input.
Added some initial code to facilitate rpm installs based on the linux distro.

**Comment by jeremyeder** [comment]
@rflorenc ok -- I read the readme.  The content is good, I just wonder if it's obvious enough being inside the pbench_bzt file.  Maybe we need man pages, or to put README_pbench_bzt.md in the higher-level "doc" folder in pbench?  I think there is markdown2man converter somewhere that could make this very easy.

Anyway...

@atheurer has laid out a list of requirements, where does pbench_bzt stand on these 6 items?
https://github.com/distributed-system-analysis/pbench/pull/148#issuecomment-175679199

**Comment by rflorenc** [comment]
We could have several README_pbench_$tool.md under pbench/agent/bench-scripts/doc with the initial description every bench script has. And maybe later turn those into man pages.

The scripts would just contain the checklist @atheurer suggested, in the beginning.

**Comment by ndokos** [comment]
Can you rebase on latest master and rename it to pbench-bzt?

**Comment by rflorenc** [comment]
@ndokos , done.

**Comment by ndokos** [comment]
Thanks!

**Comment by ndokos** [comment]
I think the plan for moving ahead with this is:

* Create a bench-scripts/config subdir and move pbench-bzt into it (the contrib directory is *not* in PATH).
* To use it currently, invoke it by its full pathname under pbench-user-benchmark:
```
pbench-user-benchmark <opts> -- /opt/pbench-agent/bench-scripts/contrib/pbench-bzt ...
```
* When pbench-bzt becomes a full benchscript (start/stop/postprocess etc), then it can be moved back into pbench-scripts.
* At that time, it will need unit tests.

Agreed?

**Comment by rflorenc** [comment]
Yes, thanks. Meanwhile I'll look further into the missing bits.

**Comment by ndokos** [comment]
I cleaned up the history and moved the script to bench-scripts/contrib. I did that in PR #207 since I wanted to get this in v0.37. Apologies if I'm out of order. Please check #207 to make sure that everything is as it should be. Thanks! Closing this.

**Pull request closed without merging**
