### PR TITLE
Add unit tests for pbench-clear-tools

### PR DESCRIPTION
**Pull request by zulcss**
Signed-off-by: Charles Short <chucks@redhat.com>
Convert pbench-clear-tools to python3 unit tests.

### CODE REVIEW

**Review by portante — COMMENTED** [review]
Looks good.  Can this be pulled out of `Draft` mode now?

**Review by riya-17 — COMMENTED** [review]
lgtm

**Review by portante — CHANGES_REQUESTED** [review]
Looks good still, but needs a rebase.

**Review by riya-17 — APPROVED** [review]

**Review by portante — CHANGES_REQUESTED** [review]
Still needs a rebase.

**Review by portante — APPROVED** [review]

**Review by dbutenhof — APPROVED** [review]

**Pull request merged**
