### PR TITLE
Remove Elasticsearch passthrough API

### PR DESCRIPTION
**Pull request by vishalvvr**
PBENCH-717

Remove Elasticsearch passthrough API

### CODE REVIEW

**Review by dbutenhof — DISMISSED** [review]
Doubly linked: both through the branch name and the git commit log! (You don't really need both, and I prefer having it in the git commit log message, but that's OK.)

**Comment by dbutenhof** [comment]
You need to run `black`:

```
lib/pbench/test/unit/server/test_requests.py
```

It's a good idea to always check with `black .`, `isort .`, and `flake8 .` (if you don't see a precommit hook) before pushing a commit, so you don't have to wait for Jenkins to complain!

**Comment by portante** [comment]
I use the following local script:

```
$ cat ~/bin/munge
#!/bin/bash
isort --profile black ${*} && black ${*} && flake8 ${*}
```

**Comment by portante** [comment]
I prefer having it in the branch name and not littering the commit messages with Red Hat internal Jira ticket references.

**Comment by dbutenhof** [comment]
Not quite:

> would reformat lib/pbench/test/unit/server/test_requests.py
>
> Oh no! 💥 💔 💥
> 1 file would be reformatted, 236 files would be left unchanged.

And:

> isort --profile black

The `black` profile is defaulted by the `project.toml` file, so just `isort` works fine.

> I prefer having it in the branch name and not littering the commit messages with Red Hat internal Jira ticket references.

I know; and I prefer it in the git log for essentially the opposite reason: I like it to show up in blame/annotations directly rather than having to traverse the extra step. (And if we don't find some decent planning alternative we're going to have to make our Jira project public anyway.)

**Review by webbnh — APPROVED** [review]
Seems OK to me (once the tests pass...).

**Review by siddardh-ra — APPROVED** [review]
:+1:

**Review by dbutenhof — APPROVED** [review]

**Pull request merged**
