### PR TITLE
 index-pbench

### PR DESCRIPTION
**Pull request by ndokos**
o Fix the duplicates exception bug similarly to the fix in the VoS tools.

o Change the index name: pbench.<year>-<month> - the month and year
  are obtained from the name of the tarball. This will require changes
  to the UI used to fetch, view and compare results.

o Change the structure of the tools info: it is now an array of dicts with keys
  for the host, its label and its tools (a dict with the tool name as the key
  and its options as the value).

o Add sosreport information: an array of dicts with keys 'md5' and 'name' with
  the obvious values.

o Grovel through the sosreports in order to get FQDN and network interface info;
  correlate with the simple hostname or IP address that is specified for remotes
  in the tools specification and add the full hostname.

o Fix exit values from index-pbench: 1 is generic error, 2 is tarball bad format
  (i.e. it does not include a metadata.log), 3 is tarball bad name (i.e. the name
  does not encode a date).

o pbench-index uses the exit values above to segregate tarballs with
  errors into different categories - no need to retry tarballs with bad format
  or bad name.

### CODE REVIEW

**Comment by ndokos** [comment]
There is a bug in pbench-index which I fixed (I think) in my fork.

**Comment by portante** [comment]
@ndokos, would it be hard to add a unit-test for pbench-index, something small that exercised a few code paths initially to help verify the generated JSON document that gets indexed?

**Comment by portante** [comment]
Looks good to me, but let's double check that toc prefix change to see if it affects yanking out sosreports.

**Comment by ndokos** [comment]
Peter Portante <notifications@github.com> writes:

> Looks good to me, but let's double check that toc prefix change to see if it affects yanking out sosreports.
>

We add the prefix back when calculating the md5 name and from that, we get the sosreport name  by just stripping the .md5 part:


    prefix = toc["toc-prefix"]
    sosreportlist = []
    for x in sosreports:
        if x.endswith('.md5'):
            d = {}
            md5 = "%s%s" % (prefix, x)
            sos = md5[:md5.rfind('.md5')]

**Comment by portante** [comment]
Can you update the sosreport ipaddr fields to use the IP Type?  See https://www.elastic.co/guide/en/elasticsearch/reference/1.5/mapping-ip-type.html

**Comment by portante** [comment]
@ndokos, can you see why the unit tests are failing now?

**Comment by ndokos** [comment]
PR#87 has changed the output of pbench_uperf (at least). I'll go through the changes and probably submit new gold files.

**Comment by ndokos** [comment]
So Andrew fixed the tools-default (dir) vs tools.default (file)
discrepancies and the PR#87 tests pass. PR#76 tests fail because
the travis host does not have python3 installed, which the index-pbench
script uses. Not sure what to do about that - I'll try changing it
to python2 but I'm not optimistic. If you have suggestions, I'm all
ears.

**Comment by ndokos** [comment]
As expected, trying it with python2 leads to a couple of problems:
FileNotFoundError is not defined in python2 and has to be replaced
with (OSError, IOError). The more significant problem is that the
exception I get is tarfile.ReadError: I think that's because the
python2 tarfile module does not know how to deal with .xz files.

**Comment by portante** [comment]
@ndokos, I believe you can specify in the `.travis.yml` file what software is required so that python3 is made available.

**Pull request merged**
