### PR TITLE
Updated benchmarks with init/end

### PR DESCRIPTION
**Pull request by Maxusmusti**

### CODE REVIEW

**Review by portante — APPROVED** [review]
Looks good!

**Review by portante — CHANGES_REQUESTED** [review]
Needs a rebase, though.

**Comment by Maxusmusti** [comment]
Rebased

**Review by portante — APPROVED** [review]
Ship it!

**Review by ndokos — APPROVED** [review]
Minor nit: we try to standardize on the use of the quoted-and-bracketed form for variable access: `${foo}`.

**Comment by portante** [comment]
> Minor nit: we try to standardize on the use of the quoted-and-bracketed form for variable access: `${foo}`.

Much of the surrounding code has the same references style, so it seems worth merging this as is since this was a glaring omission, and then we can fix the variable references up later.

**Pull request merged**
