### PR TITLE
Ensure $client is assigned before it is referenced

### PR DESCRIPTION
**Pull request by atheurer**
This should fix the problem Ben and Joe are seeing

### CODE REVIEW

**Comment by ndokos** [comment]
@atheurer: can you take a look at the failed unit tests?

**Comment by atheurer** [comment]
All of the cmd & config files for clients and servers need to be replaced in the unittest "gold" because the file names are now "correct".  For example, "client::c1-server::s2" needs to be, "client::c1-server::s1".

This is a good example of how the unittest fails to capture a problems like this in the first place.  When there is a lot of churn in the output, we often just do a wholesale replacement of the gold files.  Well, many of those files replaced were just incorrect, but since they are now the gold files, the error is never detected.  Now that the error has been fixed, the unittest fails.

**Comment by atheurer** [comment]
let me see if I can easily just rename the files in the ./gold and get the unitest to pass

**Comment by atheurer** [comment]
OK, I think we are good to go here.

**Pull request merged**
