### PR TITLE
Rename util scripts to avoid collisions.

### PR DESCRIPTION
**Pull request by ndokos**
All the util scripts now have a prefix of pbench-.

https://github.com/distributed-system-analysis/pbench/issues/64

### CODE REVIEW

**Comment by ndokos** [comment]
We can add symlinks from the old names to the new names for backwards compatibility - and we can do that in the RPM rather than adding them to the repo. After a suitable period, 
and with enough warning, we can get rid of them for a future release. Thoughts?
If that's acceptable, we can include this PR in the next release.

**Comment by atheurer** [comment]
Not sure how I feel about symlinks.  I would expect that people would just continue to use the old names, unless there's a huge warning every time they use the old name.

**Comment by portante** [comment]
In this case, I am not in favor of backward compatibility.  If they need that, I would suggest that use the existing release.  This is a sufficiently large problem for other reasons that I do not think trying to maintain backward compatibility is worth it here.

**Comment by ndokos** [comment]
The travis build is borked - I'm looking  into what needs to be done to fix it:

$ sudo pip3 install configtools elasticsearch

/usr/local/lib/python3.2/dist-packages/pip-8.0.2-py3.2.egg/pip/_vendor/pkg_resources/__init__.py:87: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.

  warnings.warn(msg)

Traceback (most recent call last):

  File "/usr/local/bin/pip3", line 9, in <module>

    load_entry_point('pip==8.0.2', 'console_scripts', 'pip3')()

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 337, in load_entry_point

    return get_distribution(dist).load_entry_point(group, name)

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2280, in load_entry_point

    return ep.load()

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1990, in load

    entry = __import__(self.module_name, globals(),globals(), ['__name__'])

  File "/usr/local/lib/python3.2/dist-packages/pip-8.0.2-py3.2.egg/pip/__init__.py", line 15, in <module>

    from pip.vcs import git, mercurial, subversion, bazaar  # noqa

  File "/usr/local/lib/python3.2/dist-packages/pip-8.0.2-py3.2.egg/pip/vcs/mercurial.py", line 9, in <module>

    from pip.download import path_to_url

  File "/usr/local/lib/python3.2/dist-packages/pip-8.0.2-py3.2.egg/pip/download.py", line 35, in <module>

    from pip.utils.ui import DownloadProgressBar, DownloadProgressSpinner

  File "/usr/local/lib/python3.2/dist-packages/pip-8.0.2-py3.2.egg/pip/utils/ui.py", line 15, in <module>

    from pip._vendor.progress.bar import Bar, IncrementalBar

  File "/usr/local/lib/python3.2/dist-packages/pip-8.0.2-py3.2.egg/pip/_vendor/progress/bar.py", line 48

    empty_fill = u'∙'

                      ^

SyntaxError: invalid syntax

**Comment by ndokos** [comment]
Re: backward compatibility - we could add a script that would take an old name, issue a big fat warning and call the new name, as Andrew suggests. If we don't provide BC, we are basically saying that if you want the new release, you *have* to go modify your scripts first. It seems to me that the transition would be harder that way.

**Comment by atheurer** [comment]
As long as we have the warning, I think that will be ok.
We will release another version next month anyway, and hopefully that one removes the older names.

**Pull request merged**
