### PR TITLE
A few changes to support tox v4.x

### PR DESCRIPTION
**Pull request by portante**

### CODE REVIEW

**Review by webbnh — APPROVED** [review]
👍

**Review by ndokos — DISMISSED** [review]

**Review by portante — COMMENTED** [review]
Ready for next round of review.

**Review by webbnh — APPROVED** [review]
Seems good.

**Review by ndokos — APPROVED** [review]

**Comment by portante** [comment]
Let's wait for @riya-17 to review before we merge it.

**Review by webbnh — DISMISSED** [review]
I don't see any changes from the last time I review this, so it must still be good.

**Review by ndokos — APPROVED** [review]

**Comment by riya-17** [comment]
> Expected end or semicolon (after version specifier)
>    setuptools >= 46.1.3.

This is present in pyproject.toml and asking to remove the dot from the end of version specifier.

**Comment by riya-17** [comment]
>Expected end or semicolon (after version specifier)
>setuptools >= 46.1.3.

This is present in pyproject.toml and asking to remove the dot from the end of version specifier.

**Review by riya-17 — APPROVED** [review]

**Review by dbutenhof — APPROVED** [review]

**Pull request merged**
