### PR TITLE
Get rid of obsolete `pbench_results_redirector` setting

### PR DESCRIPTION
**Pull request by ndokos**

### CODE REVIEW

**Review by portante — CHANGES_REQUESTED** [review]
Why are we changing the `b0.69` agent code?  Are we planning a release of it to get this change out there?

**Review by webbnh — APPROVED** [review]
LGTM

**Comment by webbnh** [comment]
> Why are we changing the `b0.69` agent code?

That's a good question...but I opted out of asking.  (I did, however, eventually prove that `pbench_results_redirector` does not appear in the current code....  😆)

**Comment by ndokos** [comment]
Just for completeness - to go with the cleanup in the internal config files.

**Review by riya-17 — APPROVED** [review]

**Review by portante — APPROVED** [review]
Since everybody else approves, I'll cave to peer pressure and approve as well.  =)

We are not going to release a b0.69 pbench-agent ever, so should not hurt anything.

**Pull request merged**
