### PR TITLE
Graph handling enhancements

### PR DESCRIPTION
**Pull request by portante**
We only show the top 20 series w/ avg >= threshold, fix some bad data handling, and start using "line with focus chart", which gives folks the ability to select a subset of the time range.

However, this are some concerns with the changes:
- Some folks might want adjust the number of series selected, the threshold used, or the even the selection method
  - Without such controls this may render some existing graphs unusable
- The use of the "line with focus chart" might add a lot of extra space to existing pages, and/or cause confusion
  - It is likely we'll want to merge this with work being done to customize a particular graph

### CODE REVIEW

**Comment by ndokos** [comment]
Can you rename bgtasks/pbench/lib/config/pbench-bgtasks.cfg to server/pbench/lib/config/pbench-bgtasks.cfg.example?

**Comment by portante** [comment]
@ndokos, I'll rebase these changes and update.

**Comment by atheurer** [comment]
Would it be possible to either toggle on/off the top 20, or allow the user
to specify the number of series?

**Comment by portante** [comment]
@atheurer, certainly possible. :)

I'd have to add more UI to do that which I have not had time for.

**Comment by atheurer** [comment]
Then I am hesitant to support this change if it cannot be easily defeated.
There may be situations where more than 20 series are necessary.

**Comment by portante** [comment]
While I agree with you that there are many graphs that need more than 20 in the series displayed, these changes are a substantial improvement for the majority of the graphs.

I was hoping we could take this change in, and then address the limitations of the 20 series as a follow-on.

Taking this change in does not mean we have to release a pbench-agent immediately, because even if we did, unless we have the web-server side changes to go along with it, it won't work.  But it does make it easier for somebody else to work on removing the limitation, especially because the limitation is made server side in the javascript, not by the post-process scripts.

**Comment by atheurer** [comment]
OK, sounds good to me.  If for some reason we don't get the enhancement to
adjust the number of series near the next release, we can then debate
reverting this.

**Comment by portante** [comment]
No longer needed, not using nvd3.

**Pull request closed without merging**
