### PR TITLE
Tool debug

### PR DESCRIPTION
**Pull request by atheurer**
This adds stdout and stderr collection to most of the tools in pbench.

These tools are all now symlinks to kvm-spinlock in ./pbench-agent/tool-scripts:

blktrace
cpuacct
dm-cache
docker
docker-info
kvm-spinlock
kvmstat
kvmtrace
numastat
openvswitch
proc-interrupts
proc-sched_debug
proc-vmstat
qemu-migrate
rabbit
sysfs
tcpdump
turbostat
virsh-migrate
vmstat

### CODE REVIEW

**Comment by portante** [comment]
@atheurer, are you using `git pull` or `git merge`?  I ask because I see merge commits in the list and you should not see any if you are using `git rebase`.

You do not have to open a new pull request when you add changes.  All you have to do is `git rebase` your current branch and do a `git push --force origin <your branch>` and the PR will be updated with the new set of changes.

**Comment by atheurer** [comment]
I merge by branch with origin/master right before issuing a pull request so I know there are no conflicts when merging my branch into master

**Comment by portante** [comment]
The best way folks have found to do that is to `git rebase`, that ensures your changes are laid on top of what is there in `master` and detects merge issues while you are rebasing at the commit that has the conflict.  It ensures that you have your working on top of the latest and not mixed in.  It also avoids repeated entires in the commit history if others are doing the same thing.

**Comment by atheurer** [comment]
OK, next time I'll use git rebase.  Since this passed all checks, can we go ahead and merge?

**Comment by portante** [comment]
I'll check it out in a few to verify.

**Comment by portante** [comment]
@atheurer, can you try rebasing now?  I get merge conflicts when I try to pull your stuff up to master.

**Comment by atheurer** [comment]
That is very odd.  Nothing has changed in master in 12 days, and this branch had no merge conflicts when the pull request was made 3 days ago.  How could it have conflicts now?

**Comment by atheurer** [comment]
# git rebase
Current branch tool-debug is up to date.

**Comment by portante** [comment]
@atheurer, did you then do a `git push --force origin tool-debug`?

**Comment by atheurer** [comment]
I did not think that was necessary since there were no changes, but I have now

**Comment by portante** [comment]
@atheurer, can you do:

```
# git co tool-debug
# git branch --set-upstream-to=origin/master tool-debug
# git rebase
```

**Comment by portante** [comment]
@atheurer, do you know how you created your `tool-debug` branch originally?  When I create development branches, I use: `git co -b tool-debug origin/master`, which automatically sets the upstream tracking to remote github repo "master", not my local master branch.

**Comment by portante** [comment]
@atheurer, so early I was the source of the confusion, as I was using a pbench clone that was from the wrong repository.  So I was able to follow the "command line instructions" and merge this by hand, rebasing the changes so that they are not interspersed by rebased on top of existing master.  We should be good now.

Merged.

**Pull request closed without merging**
