### PR TITLE
Second set of back-ports for `b0.71`

### PR DESCRIPTION
**Pull request by portante**
These 4 commits are back-ports from `main` for PRs #2814, #2816, #2822, and #2823.

They are intended to be kept separate and not squashed since they carry the original author attribution from `main`.

### CODE REVIEW

**Comment by portante** [comment]
@ldoktor, this PR contains the back-port of the `pbench-fio` fixes for the `b0.71` branch from your PR #2816.

**Review by ldoktor — DISMISSED** [review]
Looks good to me although I'd prefer keeping the full commit messages for the historic reference (in some commits it just points to a commit and PR without a detailed description, which can be problematic when different versioning system is used in the future).

**Review by dbutenhof — APPROVED** [review]

**Review by riya-17 — APPROVED** [review]

**Comment by ldoktor** [comment]
> > Looks good to me although I'd prefer keeping the full commit messages for the historic reference (in some commits it just points to a commit and PR without a detailed description, which can be problematic when different versioning system is used in the future).
> 
> There are 4 commits in this PR, which will be merged as is, so the original commit message and authorship is maintained.

Sure, I understand the first two and the last commit, my point was with regards to the https://github.com/distributed-system-analysis/pbench/pull/2836/commits/6451e1b4762757ac2d216699c5325fbe09439c39 where the original contained nice explanation while to backport omitted it. Anyway not a big deal, just pointed that out so you can decide whether you want to use that in the future. IMO it's not worth fixing inside of this PR, but might be useful to keep in mind for the future PRs.

**Review by webbnh — DISMISSED** [review]
👍

**Review by portante — COMMENTED** [review]
Corrected a bad commit message in dc02b3293.

**Review by dbutenhof — APPROVED** [review]

**Review by webbnh — APPROVED** [review]
I didn't find any changes since my last review 15 minutes ago...

**Pull request merged**
