### PR TITLE
Forward port to main some changes from b0.72

### PR DESCRIPTION
**Pull request by ndokos**
This is a forward port to main of three b0.72 PRs:

- #3440
- #3456
- #3444

They are cherry-picks of the corresponding b0.72 commits with no changes.

Set to draft mode for now to wait for #3456 to be merged first and to decide whether a single PR is a reasonable approach.  It seems reasonable to me, but if there are objections, please let me know.

### CODE REVIEW

**Comment by webbnh** [comment]
> It seems reasonable to me, but if there are objections, please let me know.

There are, as it currently stands, **_58_** files in this PR!...I vote for subdividing it.  Also, when this PR is merged, I think we're going to want it in multiple commits -- I would recommend posting a PR for each commit (or set of to-be-squashed commits) that you want to merge...which I think is three.

**Comment by ndokos** [comment]
Yes, I was planning to do three commits, one for each original b0.72 PR. I think these three are related (well, two are related in that they fix bugs in `pbench-postprocess-tools`  - among other things). How would you feel about  forward porting   #3440 and #3456 in one PR (with two commits) and doing #3444  in another?  #3444 is to blame for  42 out of the 58 files  and that would leave "only" 16 for the combined PR.

**Comment by webbnh** [comment]
> Yes, I was planning to do three commits, one for each original b0.72 PR.

The problem with that is, if there is any feedback in the PR which prompts you to add another commit, you need to add it to the end of the branch to avoid disrupting the review process, and then, once you've got approval, you need to squash the new commit(s) into the appropriate original commit(s), which then requires another round of review/approvals.

I think it's easier if we plan and intend for each PR to produce one commit.  Then, any feeback which results in additional commits can be rolled up using GitHub's squash-and-merge function without requiring an extra round of review.

> I think these three are related (well, two are related in that they fix bugs in `pbench-postprocess-tools` - among other things). How would you feel about forward porting #3440 and #3456 in one PR (with two commits) and doing #3444 in another? #3444 is to blame for 42 out of the 58 files and that would leave "only" 16 for the combined PR.

Clearly, getting the first 40+ files out into their own PR would be a huge help.  Whether we take the remaining 16 as one PR or two...I guess it depends on whether you really think of them as "one change" or not.

**Comment by ndokos** [comment]
I'll submit a forward port of #3444 to main as a separate PR.  I do think of the other two as one change, so I will try to squash them into a single commit and see how that looks. Depending on how that goes, I'll figure out what to do with them. Thanks for the comments!

**Pull request closed without merging**
