### PR TITLE
Add  --fsync-on-close option to pbench-fio

### PR DESCRIPTION
**Pull request by psuriset**
Add  --fsync-on-close option to pbench-fio to enable/disable fsync data after closer

### CODE REVIEW

**Comment by bengland2** [comment]
I want this too!  I might also need create_on_open and create_serialized for sequential writes on  distributed storage, but that will have to come later.

**Comment by portante** [comment]
The equivalent functionality is possible via the config.

**Comment by portante** [comment]
We are going to come up with a way to have certain options apply to various iterations.

**Comment by portante** [comment]
Closing in favor of tracking this in #531.

**Pull request closed without merging**
