### PR TITLE
fio-postprocess: more fixup to process fio options

### PR DESCRIPTION
**Pull request by atheurer**
Options from fio-result.txt are converted into
benchmark parameters for result.json.  This fixes
the per-job (in a job) options and concatinates those
together into a single benchmark-parameter, like:
  rw=read,read,read,write
The unittest output files for this are so old...
     -HOW OLD ARE THEY!?!
They are so old, there have been major version updates
of fio benchmark since the output files were added!
So, this update includes fio output that is actually
relevant, like output that includes the fio job options
we need to process -the whole point of this feature.

### CODE REVIEW

**Comment by atheurer** [comment]
Supersedes https://github.com/distributed-system-analysis/pbench/pull/896

**Comment by atheurer** [comment]
Re-opening this, as I have found out, trying to add more to this is just a nightmare w.r.t unittests, so let's apply this first (fix for fio parameters) and worry about the other stuff in a different PR.

**Comment by portante** [comment]
@atheurer, is this a PR you still want to get merged?

**Comment by atheurer** [comment]
@portante yes, I want this PR merged

**Pull request merged**
