### PR TITLE
 pcp-pbench: [WIP] added PCPTools(tm), PCPPmlogger(tds), PCPPmie(tds) classes and pcp-mapping.json files

### PR DESCRIPTION
**Pull request by not4win**
This PR integrates pbench with pcp. In its early stages.

File changes:
modified:   agent/util-scripts/pbench-tool-data-sink
modified:   agent/util-scripts/pbench-tool-meister
new file:   agent/util-scripts/pcp-mapping.json
new file:   agent/tool-scripts/pcptool
modified:   agent/util-scripts/gold/pbench-register-tool/test-44.txt
modified:   agent/util-scripts/gold/pbench-register-tool/test-46.txt
modified:   agent/util-scripts/gold/pbench-register-tool/test-47.txt
modified:   agent/util-scripts/pbench-tool-meister-start

### CODE REVIEW

**Comment by Maxusmusti** [comment]
The origin branch likely needs to be rebased on the tool-meister branch to reflect the most up-to-date changes (will likely reduce the files changed from 302 to the proper amount)

**Comment by not4win** [comment]
Ah heck. Yeah. Will rebase it in a while.

**Comment by not4win** [comment]
The rebase was a bit pain. But yep. Done.

**Comment by portante** [comment]
This code needs a rebase and verification.  It replaces https://github.com/portante/pbench/pull/9.

**Comment by portante** [comment]
Closing as we merged this PR into the `pcp-tool-meister` branch so that @Maxusmusti could continue this work with his PR #1956.

**Comment by portante** [comment]
Replaced by #1986.

**Pull request closed without merging**
