### PR TITLE
Disable redis protected mode

### LINKED ISSUE #3403: [BUG] redis-server refuses to start on Fedora 38
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

On Fedora 38, `redis-server` does not start:

[warn][2023-04-26T17:26:44.476406] Unable to connect to redis server,
Redis server
- dhcp31-112.perf.lab.eng.bos.redhat.com:17001: DENIED

Redis is running in protected mode because protected mode is enabled
and no password is set for the default user. In this mode connections
are only accepted from the loopback interface. If you want to connect
from external computers to Redis you may adopt one of the following
solutions:

1) Just disable protected mode sending the command 'CONFIG
SET protected-mode no' from the loopback interface by connecting to
Redis from the same host the server is running, however MAKE SURE
Redis is not publicly accessible from internet if you do so. Use
CONFIG REWRITE to make this change permanent.

2) Alternatively you can just disable the protected mode by editing
the Redis configuration file, and setting the protected mode option to
'no', and then restarting the server.

3) If you started the server manually just for testing, restart it
with the '--protected-mode no' option.

4) Setup a an authentication password for the default user. NOTE: You
only need to do one of the above things in order for the server to
start accepting connections from the outside.

Version info:

[root@dhcp31-112 ~]# uname -a
Linux dhcp31-112.perf.lab.eng.bos.redhat.com 6.2.9-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Mar 30 22:32:58 UTC 2023 x86_64 GNU/Linux

[root@dhcp31-112 ~]# redis-server --version
Redis server v=7.0.10 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=3ac3e681393b08b3

### To Reproduce

Run `pbench-user-benchmark -- sleep 20` on a Fedora 38 system with a v0.72 agent.

### Actual Results

`redis-server` issues a warning and does not start.

### Expected Results

`redis-server` should start.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ndokos**
Fixes #3403

Fedora 37 and Fedora 38 run it in protected mode by default. We probably should be doing that everywhere but for the time being, we turn it off everywhere instead.

Smoke tested against all supported distros: everybody succeeds except RHEL 7 which currently fails for unrelated reasons.

PBENCH-1163

### CODE REVIEW

**Review by dbutenhof — APPROVED** [review]
Interesting: I hadn't considered that the legacy tests might be overriding the default `tool_meister_start.py` configs.

**Comment by ndokos** [comment]
This was just an edit of the commit message of the first commit (mainly to add the ticket number).

**Comment by ndokos** [comment]
I don't think the tests are overriding the config: they are just reporting it.

**Review by webbnh — APPROVED** [review]
👍

**Comment by webbnh** [comment]
Is there a forward-port of this change for `main` coming?

**Comment by ndokos** [comment]
Maybe - but I was wondering whether it would be a good idea to enable protected mode everywhere, rather than disabling it.

**Pull request merged**
