### PR TITLE
Update references for issues and projects

### PR DESCRIPTION
**Pull request by portante**

### CODE REVIEW

**Comment by portante** [comment]
PBENCH-164 #time 5m

**Review by webbnh — APPROVED** [review]
👍

**Review by npalaska — APPROVED** [review]

**Review by dbutenhof — APPROVED** [review]
Let's get our old ducks lined up before we "retire" them and bring on the new ducks?

**Comment by dbutenhof** [comment]
We can get into issues.redhat.com from a non-Red Hat account, although our current `PBENCH` project isn't visible. I suspect there have to be ways of fixing that ... another Jira admin question, perhaps for a later time.

**Pull request merged**
