### PR TITLE
pbench-trafficgen: capture trex yaml config file

### PR DESCRIPTION
**Pull request by k-rister**
- Includes unit test update

### CODE REVIEW

**Comment by k-rister** [comment]
@portante - Is it possible to restart the Travis CI when the CI itself takes an error?

**Comment by ndokos** [comment]
@k-rister: I restarted the two that failed. In the future, you can click on "Details" in the Travis line. That should have a "Restart Job" button towards the upper right. If not, check to see if you are logged in to Travis: there might be a "Sign in with github" button that you need to push.

**Comment by ndokos** [comment]
... but the restarted job does not seem to be going anywhere.

**Comment by k-rister** [comment]
@ndokos - thanks for the instructions, I can now manage the CI myself and I'm monitoring it and restarting the jobs as needed.  Clearly Travis isn't behaving very well this morning :(

**Comment by ndokos** [comment]
Yes, it's pretty bad - I wonder if the Precise environment is rotting away under our feet. I've long wanted to turn on Trusty and see what breaks.

**Comment by k-rister** [comment]
Yeah, there are a lot of repo fails when I start looking at the logs.  It may be that mirrors are starting to drop these old repos.  Precise went EOL in April 2017...

**Comment by k-rister** [comment]
Seems like Travis is behaving again, I finally got the build to run and pass the tests.

**Comment by portante** [comment]
FWIW I did review this and it looks good, ran just fine in a RHEL 7 environment.

**Pull request merged**
