### PR TITLE
Add pbench-logo files

### PR DESCRIPTION
**Pull request by vishalvvr**
PBENCH-220

Add different color (black & colored) & shape(square & circle) logo variants.

These could be used for branding on various platforms like jira, slack, etc.

### CODE REVIEW

**Comment by portante** [comment]
FYI, you don't need the Jira issue in the commit message if you have the Jira issue as the branch name.

**Review by portante — APPROVED** [review]

**Review by webbnh — APPROVED** [review]
As I commented on #2987,

> `dashboard/src/assets/logo/color-circle.svg` looks funny, to me. Perhaps it's because I'm looking at it against the "transparent" background instead of in situ on a real page, but it strikes me that it's not properly centered in the circle. I'm not absolutely positive, but I think the "center" of the logo should be between the e and the n and not at the base of the pointer.

If we're going to center the logo on the base of the pointer, then the gray arch that the pointer is pointing to should be reshaped to match the radius of the pointer which would also be the arch of the surrounding circle.

**Comment by webbnh** [comment]
> FYI, you don't need the Jira issue in the commit message if you have the Jira issue as the branch name.

Since the branch is likely to disappear when it is merged, it's probably _better_ to have it in the commit message....

**Comment by portante** [comment]
> > FYI, you don't need the Jira issue in the commit message if you have the Jira issue as the branch name.
> 
> Since the branch is likely to disappear when it is merged, it's probably _better_ to have it in the commit message....

I believe the record of where it is merged from is kept in the closed PR (e.g. https://github.com/distributed-system-analysis/pbench/pull/2790).

**Comment by portante** [comment]
> As I commented on #2987,
> 
> > `dashboard/src/assets/logo/color-circle.svg` looks funny, to me. Perhaps it's because I'm looking at it against the "transparent" background instead of in situ on a real page, but it strikes me that it's not properly centered in the circle. I'm not absolutely positive, but I think the "center" of the logo should be between the e and the n and not at the base of the pointer.
> 
> If we're going to center the logo on the base of the pointer, then the gray arch that the pointer is pointing to should be reshaped to match the radius of the pointer which would also be the arch of the surrounding circle.

Are these logos just lifted and posted to this repository from the now archived pbench-dashboard (see https://github.com/distributed-system-analysis/pbench-dashboard/tree/main/media)?

If so, then we don't want to change them in this PR.  If these images are newly created, then we might want to consider fixing them.

**Comment by webbnh** [comment]
> > > FYI, you don't need the Jira issue in the commit message if you have the Jira issue as the branch name.
> > 
> > 
> > Since the branch is likely to disappear when it is merged, it's probably _better_ to have it in the commit message....
> 
> I believe the record of where it is merged from is kept in the closed PR (e.g. #2790).

Yeah, but, if you're looking at the sources, you go from there to a commit; if the reference to the issue isn't in the commit log, then you have to go to the PR (assuming that it still exists), and read through it looking for branch references in the history to see if any of them happen to include the Jira tag.

It seems like it would be simpler to just put the Jira tag in the commit log -- then no PR or even GitHub itself is required to find it....

**Comment by portante** [comment]
The branch name it is merged from is right at the top of the PR page.

**Comment by portante** [comment]
They even given you a little copy button to copy it from.  See the top of this PR.

**Comment by webbnh** [comment]
And, better still, the branch name is a hyperlink!...which leads directly to...a 404.  😆 

Seriously, though, the difference is that the Git history is available in ways and places that the PR is not.  Why should we require that GitHub be the link between Git and Jira when we have the option of linking them directly?

**Review by siddardh-ra — APPROVED** [review]
:+1:

**Pull request merged**
