### PR TITLE
New and Unmanaged runs header

### PR DESCRIPTION
**Pull request by MVarshini**
PBENCH-1265

New and Unmanaged runs header

### CODE REVIEW

**Review by dbutenhof — APPROVED** [review]
Cool; this seems to work, although it leaves the "Display metadata" control as well, which currently isn't of any use with an empty unmanaged list. (But that'll change with #3546, so that's fine.)

I did notice that when I bulk-selected all the unmanaged runs and then selected "save" from the popup, the display didn't update. I had to switch away to another view and then come back before they all moved down. But that should probably be handled separately anyway. 😆

**Comment by MVarshini** [comment]
> Cool; this seems to work, although it leaves the "Display metadata" control as well, which currently isn't of any use with an empty unmanaged list. (But that'll change with #3546, so that's fine.)
> 
> I did notice that when I bulk-selected all the unmanaged runs and then selected "save" from the popup, the display didn't update. I had to switch away to another view and then come back before they all moved down. But that should probably be handled separately anyway. 😆

Updating the saved runs view issue also fixed :wink:

**Comment by dbutenhof** [comment]
> npx eslint --max-warnings 0 "src/**"
>
>/home/jenkins/pbench/dashboard/src/modules/components/OverviewComponent/index.jsx
  33:58  warning  'isMetadataModalOpen' is assigned a value but never used  no-unused-vars
>
>✖ 1 problem (0 errors, 1 warning)

**Review by dbutenhof — APPROVED** [review]

**Review by webbnh — APPROVED** [review]
👍

**Pull request merged**
