### PR TITLE
Fix stand-alone use of `pbench-make-result-tb`

### LINKED ISSUE #2360: pbench-make-result-tb won't create tarball
Version: pbench-agent `0.69.8-20g90314ee7c`

`pbench-make-result-tb` won't create tarball from a target directory.

```
# pbench-make-result-tb --result-dir=/var/lib/pbench-agent/fio__2021.06.11T14.26.42/ --target-dir=./tardir/
```

Command exits with 0 exit code, does not emit any warning or traceback, but does not create tarball.

### PR DESCRIPTION
**Pull request by portante**
Forward port of PR #2404, which fixes #2360.

### CODE REVIEW

**Review by ndokos — CHANGES_REQUESTED** [review]
l.199 has the same problem as in #2404 I think.

**Review by webbnh — DISMISSED** [review]
As I [said](https://github.com/distributed-system-analysis/pbench/pull/2404#pullrequestreview-723715944) in #2404, I think Nick's concern is accurate but not a problem; however, I think that the change made at line 111 should presumably be made to line 198 as well.

**Review by webbnh — DISMISSED** [review]

**Review by ndokos — CHANGES_REQUESTED** [review]
As in #2404, this will not work if `target-dir` is a relative pathname.

**Comment by webbnh** [comment]
I forward-ported the late-breaking changes from #2404, as well as two other items:
- I removed an errant blank character from the beginning of a line (we use hard-tabs for indentation in this file)
- I removed the quotes around an invocation of `basename` -- since we assign the results directly to a shell variable, we don't need to protect them against word-splitting.

**Review by dbutenhof — DISMISSED** [review]
I think that looks as it should ...

**Review by ndokos — DISMISSED** [review]

**Review by riya-17 — APPROVED** [review]
It looks good

**Review by dbutenhof — APPROVED** [review]

**Pull request merged**
