### PR TITLE
Support the use of tox v4.x

### PR DESCRIPTION
**Pull request by portante**

### CODE REVIEW

**Review by webbnh — DISMISSED** [review]

**Review by dbutenhof — APPROVED** [review]
Interesting. Since I missed the overflow part of the overflow... I presume/hope this change is compatible with the `tox` we're currently using, since the PR doesn't include a dependency update and the CI seems to have succeeded ... 👍🏻

**Review by ndokos — DISMISSED** [review]

**Comment by portante** [comment]
> I presume/hope this change is compatible with the `tox` we're currently using, since the PR doesn't include a dependency update and the CI seems to have succeeded ... 👍🏻

Yes, basically `tox` v4.x removes recognition of the configuration `whitelist_externals`.  The replacement, `allowlist_externals`, does not work with the version of tox installed via RPMs available to Fedora 33 (the container image being used in the CI jobs for the `b0.69` branch).

However, we are using a version of Fedora in our CI which installs a version of `tox` via RPM which does properly work with `allowlist_externals` (v3.26+ seems to work fine).

This change "should" work, but I don't have a tox `v4` environment handy to verify.

I'd be great of Riya could verify that her `tox --version` is v4.x and that this works.

**Review by webbnh — DISMISSED** [review]
👍

**Review by ndokos — DISMISSED** [review]

**Comment by riya-17** [comment]
> Expected end or semicolon (after version specifier)
> setuptools >= 46.1.3.

This is present in pyproject.toml and asking to remove the dot from the end of version specifier.

**Review by riya-17 — APPROVED** [review]

**Review by ndokos — APPROVED** [review]

**Pull request merged**
