### PR TITLE
Sysstat fixes and CDM

### PR DESCRIPTION
**Pull request by atheurer**
- speed-up of sar and mpstat postprocess
- generate CDM for sar, pidstat, mpstat and iostat
- fixes for missing sar data
- fixes for log_cdm_metric_sample/gen_cdm_metric_data

### CODE REVIEW

**Comment by atheurer** [comment]
That is really odd, as when I run, I get no errors:

<pre>[atheurer@perf84 pbench]$ cd agent/tool-scripts/postprocess/
[atheurer@perf84 postprocess]$ ./unittests
Testing bench-scripts/postprocess/compare-bench-results under sample compare-bench-results-0 ...
PASS - compare-bench-results-0
Testing cpuacct-postprocess under sample cpuacct ...
PASS - cpuacct
Testing disk-postprocess under sample disk ...
PASS - disk
Testing docker-postprocess under sample docker ...
PASS - docker
Testing bench-scripts/postprocess/fio-postprocess under sample fio-0 ...
PASS - fio-0
Testing bench-scripts/postprocess/generate-benchmark-summary under sample generate-benchmark-summary-0 ...
PASS - generate-benchmark-summary-0
Testing haproxy-ocp-postprocess under sample haproxy-ocp ...
PASS - haproxy-ocp
Testing iostat-postprocess under sample iostat-0 ...
PASS - iostat-0
Testing iostat-postprocess under sample iostat-1 ...
PASS - iostat-1
Testing iostat-postprocess under sample iostat-2 ...
PASS - iostat-2
Testing iostat-postprocess under sample iostat-3 ...
PASS - iostat-3
Testing jmap under sample jmap ...
PASS - jmap
Testing jstack under sample jstack ...
PASS - jstack
Testing kvmstat-postprocess under sample kvmstat ...
PASS - kvmstat
Testing mpstat-postprocess under sample mpstat ...
PASS - mpstat
Testing mpstat-postprocess under sample mpstat-0 ...
PASS - mpstat-0
Testing mpstat-postprocess under sample mpstat-1 ...
PASS - mpstat-1
Testing pcp-postprocess under sample pcp-0 ...
PASS - pcp-0
Testing pidstat-postprocess under sample pidstat-0 ...
PASS - pidstat-0
Testing pidstat-postprocess under sample pidstat-1 ...
PASS - pidstat-1
Testing pidstat-postprocess under sample pidstat-2 ...
PASS - pidstat-2
Testing pidstat-postprocess under sample pidstat-3 ...
PASS - pidstat-3
Testing proc-interrupts-postprocess under sample proc-interrupts-0 ...
PASS - proc-interrupts-0
Testing proc-interrupts-postprocess under sample proc-interrupts-1 ...
PASS - proc-interrupts-1
Testing proc-vmstat-postprocess under sample proc-vmstat ...
PASS - proc-vmstat
Testing bench-scripts/postprocess/process-iteration-samples under sample process-iteration-samples-0 ...
PASS - process-iteration-samples-0
Testing prometheus-metrics-postprocess under sample prometheus-metrics ...
PASS - prometheus-metrics
Testing sar-postprocess under sample sar-0 ...
PASS - sar-0
Testing sar-postprocess under sample sar-1 ...
PASS - sar-1
Testing sar-postprocess under sample sar-2 ...
PASS - sar-2
Testing sar-postprocess under sample sar-3 ...
PASS - sar-3
Testing sar-postprocess under sample sar-4 ...
PASS - sar-4
Testing sar-postprocess under sample sar-5 ...
PASS - sar-5
Testing bench-scripts/postprocess/uperf-postprocess under sample uperf-0 ...
PASS - uperf-0
Testing bench-scripts/postprocess/uperf-postprocess under sample uperf-1 ...
PASS - uperf-1
Testing bench-scripts/postprocess/uperf-postprocess under sample uperf-2 ...
PASS - uperf-2
Testing bench-scripts/postprocess/uperf-postprocess under sample uperf-3 ...
PASS - uperf-3
Testing vmstat-postprocess under sample vmstat ...
PASS - vmstat</pre>

Did you have other sar(-1-4) fail as well?  I would have expected all of them to fail if your sar-5 failed in that way.

The errors:
<pre>+ "create_metric_desc_doc" is not exported by the PbenchCDM module
+  "create_metric_data_doc" is not exported by the PbenchCDM module
+  "log_cdm_metric_sample" is not exported by the PbenchCDM module
+  "gen_cdm_metric_data" is not exported by the PbenchCDM module</pre>

Sound like they could have happened if the PbenchCDM module was not present, but it should be (under ./agent/lib).  However, create_metric_desc_doc and create_metric_data_doc are not needed by the sysstat postprocessors, so I'll take that out of the line "use PbenchCDM qw(create_metric_desc_doc create_metric_data_doc log_cdm_metric_sample gen_cdm_metric_data);" from all of the sysstat postprocessors and update the PR.  That still won't fix the underlying problem but will at least remove unnecessary functions being requested.

**Comment by portante** [comment]
Yes, it failed on all the sar files.  I'll report back more details in a bit.

**Comment by portante** [comment]
All sar, iostat, pidstat, mpstat tool-scsripts/postprocessing tests fail with the above error.

**Comment by portante** [comment]
This appears to be a test environment setup issue.  We need to do the same changes we did on the server side to properly use the config "activate" script on the agent side.  If we really want to solve this cleanly.

I am going to take a look at what that would entail.

**Comment by portante** [comment]
Filed PR #1204 to fix the base problem.

**Comment by atheurer** [comment]
Adding "do not merge" label until I clean up PR and add a few fixes for CDM processing".  I expect this will be done end of Monday 5/20.

**Comment by atheurer** [comment]
Replaced with https://github.com/distributed-system-analysis/pbench/pull/1207

**Pull request closed without merging**
