### PR TITLE
RPMs were renamed to prepend pbench- and this function was not updated

### PR DESCRIPTION
**Pull request by jeremyeder**

### CODE REVIEW

**Comment by jeremyeder** [comment]
```
root@288bcd4be2ec: ~ # pbench-uperf --server=localhost --client=localhost
[error][20160407_12:10:12.577622854] [check_install_rpm] the installation of uperf-1.0.4 failed
[error][20160407_12:10:12.580228316] [pbench-uperf]uperf installation failed, exiting
root@288bcd4be2ec: ~ # rpm -qa|grep uperf
pbench-uperf-1.0.4-1.x86_64
```

**Comment by jeremyeder** [comment]
nope...doesn't always work. this breaks pbench-register-tool-set

```
# pbench-register-tool-set                                                                                                                                                                     
[error][20160407_12:45:31.899243167] [check_install_rpm] the installation of pbench-pbench-sysstat-11.2.0 failed
For some reason this tool could not be installed
[error][20160407_12:45:32.561372484] [check_install_rpm] the installation of pbench-pbench-sysstat-11.2.0 failed
For some reason this tool could not be installed
[error][20160407_12:45:33.206289975] [check_install_rpm] the installation of pbench-pbench-sysstat-11.2.0 failed
For some reason this tool could not be installed
[error][20160407_12:45:33.844992434] [check_install_rpm] the installation of pbench-pbench-sysstat-11.2.0 failed
For some reason this tool could not be installed
proc-vmstat tool is now registered in group default
proc-interrupts tool is now registered in group default
[error][20160407_12:45:34.812681428] [check_install_rpm] the installation of pbench-kernel-tools failed
pbench is running inside a KVM guest.  Disabling turbostat.
For some reason this tool could not be installed
perf tool is now registered in group default
```

**Comment by jeremyeder** [comment]
```
# pbench-fio --test-types=read --runtime=10 --block-sizes=1024 --file-size=10
[error][20160407_13:33:05.561176708] [check_install_rpm] the installation of fio-2.2.5 failed
```

**Comment by ndokos** [comment]
The function checks more than pbench-* RPMs so it should not be modified. The callers need to call it with the correct RPM name, which sometimes has a pbench- prefix and sometimes not.

I checked the tool scripts and everything seems OK there. The benchmark scripts should use $0 (e.g. pbench-uperf) and therefore *should* get the right name, but I'm double checking them.

**Comment by ndokos** [comment]
They hardwire the benchmark name :-( I'll open a PR to fix them.

**Comment by ndokos** [comment]
PR #211

**Pull request closed without merging**
